[marcus.min] Step 3 - review
2023newkrew/spring-roomesacpe-auth-kakao pull request #104
Opened 2023-02-01 08:14 UTC by ekzm8523

안녕하세요 웨이드!
웨이드가 남겨주신 리뷰 반영하는 도중 머지가 되었더라구요!!
과제는 완료되었지만 궁금한게 있어서 PR을 하나 새로 만들게 되었습니다.

## 변경점
- Role Enum 추가
- AdminOnly에 LoginRequired 어노테이션 추가

## 봐주셨으면 하는 부분
`preHandle` & `getRoleIfRequiredAuthorization` 
메서드에서  LoginRequired와 AdminOnly의 어노테이션을 파싱하는 부분을 최대한 함수형 프로그래밍으로 짜려고 노력을 했습니다.
아래 현재 코드와 If 문으로 만든 코드를 각각 나열해 보았는데 어떤게 더 가독성이 좋다고 느껴지시나요?
혹은 더 클린한 코드 있을까요?

### 현재 코드
```
    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) {
        getRoleIfRequiredAuthorization(handler).ifPresent(
                requiredRole -> {
                    setAccessTokenToRequestAttribute(request);
                    if (requiredRole.isAdmin()) {
                        checkAdmin(request);
                    }
                }
        );
        return true;
    }

    private Optional<Role> getRoleIfRequiredAuthorization(Object handler) {
        HandlerMethod handlerMethod = (HandlerMethod) handler;

        return Stream.of(handlerMethod.getMethodAnnotation(LoginRequired.class),
                        handlerMethod.getMethodAnnotation(AdminOnly.class),
                        handlerMethod.getMethod().getDeclaringClass().getAnnotation(LoginRequired.class),
                        handlerMethod.getMethod().getDeclaringClass().getAnnotation(AdminOnly.class)
                )
                .filter(Objects::nonNull)
                .map(annotation -> ((LoginRequired) annotation).requiredRole())
                .findFirst();
    }
```

### If 문으로 만든 코드
```
    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) {
        Optional<Role> role = getRoleIfRequiredAuthorization(handler);
        if (role.isEmpty()) {
            return true;
        }
        setAccessTokenToRequestAttribute(request);
        if (role.get().isAdmin()) {
            checkAdmin(request);
        }
        return true;
    }

    private Optional<Role> getRoleIfRequiredAuthorization(Object handler) {
        HandlerMethod handlerMethod = (HandlerMethod) handler;
        
        if (handlerMethod.getMethodAnnotation(LoginRequired.class) != null) {
            return Optional.of(handlerMethod.getMethodAnnotation(LoginRequired.class).requiredRole());
        }

        if (handlerMethod.getMethod().getDeclaringClass().getAnnotation(LoginRequired.class) != null){
            return Optional.of(handlerMethod.getMethod().getDeclaringClass().getAnnotation(LoginRequired.class).requiredRole());
        }
        
        if (handlerMethod.getMethodAnnotation(AdminOnly.class) != null) {
            return Optional.of(((LoginRequired) handlerMethod.getMethodAnnotation(AdminOnly.class)).requiredRole());
        }

        if (handlerMethod.getMethod().getDeclaringClass().getAnnotation(AdminOnly.class) != null) {
            return Optional.of(((LoginRequired) handlerMethod.getMethod().getDeclaringClass().getAnnotation(AdminOnly.class)).requiredRole());
        }

        return Optional.empty();
    }
```

2023-02-01 08:47 UTC, wade-lim requested changes
다음 과제랑 다른 교육 때문에 바쁘실 줄 알고 너무 성급하게 머지했네요 🥲

사소한 리뷰 몇 개 남겼습니다!

2023-02-01 08:47 UTC, wade-lim commented on src/main/java/nextstep/auth/annotation/AdminOnly.java
> +@LoginRequired(requiredRole = Role.ADMIN)
[질문]
따로 AdminOnly 를 만드신 의도가 있나요?
Annotation 이 불필요하게 늘어나는 느낌이 있어서요~

2023-02-01 08:47 UTC, wade-lim commented on src/main/java/nextstep/auth/interceptor/AuthInterceptor.java
> +                }
[의견]
권한이 수직적인 관계라면 Role 쪽에 level 과 같은 변수를 두고 requiredRole.level() 이 token 의 role level 이상인지 체크하는 것도 좋아보여요!

2023-02-01 10:18 UTC, ekzm8523 commented on src/main/java/nextstep/auth/annotation/AdminOnly.java
> +@LoginRequired(requiredRole = Role.ADMIN)
어노테이션 이름으로 명확하게 구별하기 위해서 따로 만들었는데 어노테이션은 상속의 개념이 없어서 그런지 코드를 더 복잡하게 만든 느낌이 들긴 하네요 😭

2023-02-01 11:02 UTC, ekzm8523 commented on src/main/java/nextstep/auth/interceptor/AuthInterceptor.java
> +                }
@wade-lim 반영하였습니다 😊

2023-02-02 01:33 UTC, wade-lim approved these changes
👍

2023-02-02 01:33 UTC, merged