[jaws.bar] 방탈출 인증 관리 1, 2단계
2023newkrew/spring-roomesacpe-auth-kakao pull request #17
Opened 2023-01-17 08:44 UTC by park0503

## 구현 기능
- [1단계 요구 사항](https://edu.nextstep.camp/s/GiKTqpMP/ls/1avGK1MF)에 맞춰 인증 관리 1단계를 구현했습니다.
  - 토큰 발급 및 내 정보 조회에 대한 컨트롤러 통합 테스트를 추가로 작성했습니다.
- [2단계 요구 사항](https://edu.nextstep.camp/s/GiKTqpMP/ls/BZyLwLF7)에 맞춰 인증 관리 2단계를 구현했습니다.
  - `HanlderMethodArgumentResolver` 및 `MvcConfig`, `LoginInterceptor` 등을 이용해 구현했습니다.
  - 개선된 예약하기, 예약취소에 대해 컨트롤러 통합 테스트를 추가로 작성했습니다.
- 스켈레톤 코드를 전체적으로 리팩토링 했습니다.
  - Lombok 적용
  - final 변수 적용

### 감사합니다.

2023-01-17 18:01 UTC, gayeon1025 requested changes
안녕하세요 죠스~ 휴가동안 진짜 엄청난 리뷰의 현장을 목도하고 왔더니 엗웓만큼 잘 할 자신은 없지만 나름 열심히 리뷰드려보겠습니다!

1. 요구사항에 대한 테스트가 있으면 좋을 것 같아요! (저도 TC 짜는 게 세상 귀찮아요ㅠㅠㅠ)
  - 로그인이 되었을 때/되어있지 않을 때 각각의 경우에 예약이 성공/실패하는지 테스트
  - 토큰이 없을 때 /requests/** 에 접근이 불가한지 확인할 수 있는 테스트. 그 이외의 요청에는 토큰이 없어도 응답을 받을 수 있는지 테스트

2. 요청응답이 내려오지 않는 것 같습니다ㅠㅠ
 1단계 요구사항 구현을 확인중이었는데요. /login/token 의 응답으로 500 status를 받고 있습니다. 저의 재현 단계는 아래와 같습니다.

```
// (1) 멤버등록
curl --location --request POST 'localhost:8080/members' \
--header 'Content-Type: application/json' \
--data-raw '{
    "username": "user1",
    "password": "1111",
    "name": "user",
    "phone": "010-1234-1234"
}'

// 토큰발급
curl --location --request POST 'localhost:8080/login/token' \
--header 'Content-Type: application/json' \
--data-raw '{
    "username": "user1",
    "password": "1111"
}'
```

2023-01-17 18:01 UTC, gayeon1025 commented on src/main/java/nextstep/member/Member.java
> +@NoArgsConstructor
@NoArgsConstructor, @AllArgsConstructor, @RequriedArgsConstructor 어노테이션 내부에 들어가보면 access라는 필드가 있습니다! 생성자의 접근제어 지시자를 지정할 수 있는 필드인데요! 아무곳에서나 불리지 않도록 access 레벨을 최소로 지정해주면 좋을 것 같아요!

2023-01-17 18:01 UTC, gayeon1025 commented on src/main/java/nextstep/member/MemberRequest.java
> +@NoArgsConstructor
MemberRequest의 기본생성자가 쓰이는 곳이 있나요? 쓰이는 곳이 없다면 @NoArgsConstructor를 꼭 모든 모델마다 붙이지 않는 것이 좋을 것 같습니다!

2023-01-17 18:01 UTC, gayeon1025 commented on src/main/java/nextstep/reservation/ReservationController.java
>  public class ReservationController {
아마 리팩토링하시면서 누락된 것 같은데  ReservationController에 ExceptionHandler가 남아있는 것 같습니다!

2023-01-17 18:01 UTC, gayeon1025 commented on src/main/java/nextstep/reservation/ReservationService.java
>          }
(사실 요건 취향의 영역일 수 있지만) if문 내부의 `!Objects.equals(reservation.getMemberId(), memberId)` 로직을 `isNotMine()`등의 메서드로 다로 추출하면 읽기에 좋을 것 같은데 어떻게 생각하시나요?

2023-01-17 18:01 UTC, gayeon1025 commented on src/main/java/nextstep/interceptor/LoginInterceptor.java
> +        String accessToken = request.getHeader("authorization").split(" ")[1];
api 요청시에 authorization 헤더를 누락한 경우 NPE가 발생할 수 있습니다!!

2023-01-17 18:01 UTC, gayeon1025 commented on src/main/java/nextstep/interceptor/LoginInterceptor.java
> +            throw new RoomReservationException(ErrorCode.AUTHENTICATION_REQUIRED);
죠스는 물론 알고 계실 것 같지만 authentication과 authorization의 차이에 대해서 언급한 블로그가 있어 추가로 드려봅니다~
📌 [인증과 인과](https://velog.io/@aaronddy/%EC%9D%B8%EC%A6%9DAuthentication%EA%B3%BC-%EC%9D%B8%EA%B0%80Authorization)

2023-01-17 18:01 UTC, gayeon1025 commented on src/main/java/nextstep/config/WebMvcConfig.java
> +                .addPathPatterns("/members/me");
이것도 정답은 아니고 저의 취향?인 것 같지만ㅋㅋ 
만약 권한을 필터링해야하는 path들이 많아진다고 했을 때 .properties 파일을 활용할 수 있지 않을까요? 혹시 죠스가 생각하시기에 다른 좋은 방법이 있다면 알려주세요~

2023-01-18 03:55 UTC, park0503 commented on src/main/java/nextstep/member/Member.java
> +@NoArgsConstructor
헉 잊고 있던 내용이네요. 감사합니다!

2023-01-18 03:55 UTC, park0503 commented on src/main/java/nextstep/member/MemberRequest.java
> +@NoArgsConstructor
request dto나 모델에 `@NoArgsConstructor` 어노테이션을 붙이지 않으면 jackson 메시지 컨버터에서 역직렬화 에러가 발생하더라구요. 필드에 `@JsonProperty` 어노테이션을 붙이는 방법도 있게지만, 빈 생성자를 만드는 것이 더 간단한 것 같아 위와 같이 적용했습니다.

2023-01-18 03:55 UTC, park0503 commented on src/main/java/nextstep/reservation/ReservationController.java
>  public class ReservationController {
넵 바로 지워 줘야겠네요!

2023-01-18 03:58 UTC, park0503 commented on src/main/java/nextstep/reservation/ReservationService.java
>          }
도메인 클래스 내에 로직을 위치시키면 어떻냐는 말씀이시죠?
간단한 부분이라 그냥 넘겼는데, 코드가 더 깔끔해 보일 수 있을 것 같습니다.
적용하겠습니다!

2023-01-18 03:58 UTC, park0503 commented on src/main/java/nextstep/interceptor/LoginInterceptor.java
> +        String accessToken = request.getHeader("authorization").split(" ")[1];
예외처리가 미숙했네요! 적용하겠습니다.

2023-01-18 04:02 UTC, park0503 commented on src/main/java/nextstep/interceptor/LoginInterceptor.java
> +            throw new RoomReservationException(ErrorCode.AUTHENTICATION_REQUIRED);
넵 해당 부분은 로그인이 실패한 경우 발생하는 예외를 처리해 준 것으로 인증 (Authentication) 관련 에러 코드를 삽입해 주었습니다.
해당 에러코드의 경우 401 unauthorized의 status를 가지는데 이는 authorize란 이름과 다르게 해당 http status가 인증 실패를 나타내는 것으로 알고 있어서 입니다!

헤더의 경우 요구사항에 authorization이란 이름으로 토큰을 담아 요청했기 때문에 그대로 구현했습니다.

좋은 자료 첨부 감사합니다!

2023-01-18 04:07 UTC, park0503 commented on src/main/java/nextstep/config/WebMvcConfig.java
> +                .addPathPatterns("/members/me");
생각해보지 못한 방법인데 application.properties에 /reservation/** 과 같은 path를 따로 등록하고 이를 가져다 쓰는 방식을 말씀하시는 걸까요?

2023-01-18 04:08 UTC, park0503 commented on src/main/java/nextstep/member/MemberRequest.java
> +@NoArgsConstructor
[제가 에러 발생 시 참고했던 링크](https://stackoverflow.com/questions/53191468/no-creators-like-default-construct-exist-cannot-deserialize-from-object-valu) 입니다!

2023-01-18 04:55 UTC, park0503 commented
@gayeon1025 
피드백 반영 완료했습니다!...만 궁금한 점이 몇가지 생겨 질문 드립니다.
1. RequestDto 클래스의 경우 요청을 객체로 치환하는 작업을 message converter에서 수행하기에 기본 생성자가 없을 시 역직렬화 에러가 발생하는 것은 이해가 가는데, domain 클래스에서도 왜  같은 에러가 발생하는지 궁금합니다. 도메인 클래스는 응답으로 사용되기에 반대로 직렬화 에러가 발생하는 것이 맞지 않은가요?
2. 테스트를 작성하는데 RestAssured를 사용한 테스트들은 `@Nested` 어노테이션을 이용해 묶으니 `connection refused` 에러가 발생하더라구요. 포트 문제인가 싶어 테스트 환경을 RANDOM_PORT로도 수정해 보고 했는데도 해결하지 못해 테스트 메소드들이 조금 난잡하게 배치되어 있는 상황입니다. 이러한 문제가 발생하는 원인이 무엇일까요?

2023-01-19 00:59 UTC, gayeon1025 commented on src/main/java/nextstep/member/MemberRequest.java
> +@NoArgsConstructor
@park0503 안녕하세요 죠스! 혹시 익셉션 재현 상황을 구체적으로 더 알 수 있을까요? 
제가 로컬에서 MemberRequest의 @NoArgsConstructor를 제거하고 <(1)멤버등록>, <(2)토큰발급>, <(3)내 정보 조회>를 진행했는데 정상 응답을 받았습니다. 

> 기본 생성자가 없을 시 역직렬화 에러가 발생하는 것은 이해가 가는데, domain 클래스에서도 왜 같은 에러가 발생하는지 궁금합니다.
3가지 과정 모두 통과한 것으로 보아 죠스가 질문주신 부분도 저에게는 재현이 안 되고 있는 것 같습니다...

2023-01-19 01:48 UTC, park0503 commented on src/main/java/nextstep/member/MemberRequest.java
> +@NoArgsConstructor
제 환경에서는 @NoArgsConstructor를 제거하면 멤버 등록 부분에서 문제가 발생합니다. 혹시 테스트 시에만 발생하나 싶어 서버를 띄우고 curl 명령어로 요청을 날려 봐도 같은 에러가 발생했습니다. 다음은 에러 전문입니다.
```
org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class nextstep.member.MemberRequest]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `nextstep.member.MemberRequest` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 2, column: 5]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:388) ~[spring-web-5.3.22.jar:5.3.22]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:343) ~[spring-web-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:185) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:160) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:133) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:122) ~[spring-web-5.3.22.jar:5.3.22]
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:179) ~[spring-web-5.3.22.jar:5.3.22]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:146) ~[spring-web-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1070) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[tomcat-embed-core-9.0.65.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.65.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.22.jar:5.3.22]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.22.jar:5.3.22]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.22.jar:5.3.22]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at net.rakugakibox.spring.boot.logback.access.tomcat.LogbackAccessTomcatValve.invoke(LogbackAccessTomcatValve.java:91) ~[logback-access-spring-boot-starter-2.7.1.jar:2.7.1]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na [...]

2023-01-19 04:09 UTC, gayeon1025 commented on src/main/java/nextstep/member/MemberRequest.java
> +@NoArgsConstructor
@park0503 흠... 제 로컬에서는 재현이 안 되네요ㅠㅠ 저는 exception 발생하지 않고 성공하네요ㅠㅠ
에러 메시지 내용을 보니 죠스가 해주신 방법이 일단 적절한 대처인 듯 싶으니 이대로 두고 다음 과제를 진행하는 게 좋겠어요

2023-01-19 04:55 UTC, park0503 commented on src/main/java/nextstep/member/MemberRequest.java
> +@NoArgsConstructor
@gayeon1025 도대체 무슨 현상일까요 이건.. ㅜㅜㅜ
알겠습니다 3단계로 넘어가도 될까요?

2023-01-19 05:24 UTC, gayeon1025 commented
@park0503 
> 테스트를 작성하는데 RestAssured를 사용한 테스트들은 @Nested 어노테이션을 이용해 묶으니 connection refused 에러가 발생하더라구요. 포트 문제인가 싶어 테스트 환경을 RANDOM_PORT로도 수정해 보고 했는데도 해결하지 못해 테스트 메소드들이 조금 난잡하게 배치되어 있는 상황입니다. 이러한 문제가 발생하는 원인이 무엇일까요?

흠... RestAssured를 저는 써본 적이 없어서 큰 도움은 안 되는 것 같아 죄송합니다ㅠㅠ (저희는 그냥 간단한 전역 테스트는 WebTestClient로 확인하고 있습니다. 이렇게 쓰시라는 건 아니고!! 그냥 궁금하실까봐ㅎㅎ)
제가 잠깐 돌려봤을 때 @Nested를 붙이지 않고 PORT만 RANDOM_PORT로 수정해도 Connection refused가 발생하네요..

RestAssured 버전도 현재 버전은 5.3.0인데 3.3.0을 쓰고 계시던데, 빌드 시에 충돌이 나서 이전 버전을 쓰신걸까요? 
추가로 docs를 잠시 봤는데 이런 주의 사항도 있었네요😳

> You should place rest-assured before the JUnit dependency declaration in your pom.xml / build.gradle in order to make sure that the correct version of Hamcrest is used.

2023-01-19 05:27 UTC, gayeon1025 approved these changes
@park0503

> 테스트를 작성하는데 RestAssured를 사용한 테스트들은 @nested 어노테이션을 이용해 묶으니 connection refused 에러가 발생하더라구요. 포트 문제인가 싶어 테스트 환경을 RANDOM_PORT로도 수정해 보고 했는데도 해결하지 못해 테스트 메소드들이 조금 난잡하게 배치되어 있는 상황입니다. 이러한 문제가 발생하는 원인이 무엇일까요?

흠... RestAssured를 저는 써본 적이 없어서 큰 도움은 안 되는 것 같아 죄송합니다ㅠㅠ (저희는 그냥 간단한 전역 테스트는 WebTestClient로 확인하고 있습니다. 이렇게 쓰시라는 건 아니고!! 그냥 궁금하실까봐ㅎㅎ)
제가 잠깐 돌려봤을 때 @nested를 붙이지 않고 PORT만 RANDOM_PORT로 수정해도 Connection refused가 발생하네요..

RestAssured 버전도 현재 버전은 5.3.0인데 3.3.0을 쓰고 계시던데, 빌드 시에 충돌이 나서 이전 버전을 쓰신걸까요?
추가로 docs를 잠시 봤는데 이런 주의 사항도 있었네요😳
> You should place rest-assured before the JUnit dependency declaration in your pom.xml / build.gradle in order to make sure that the correct version of Hamcrest is used.


해당 이슈는 주요 문제는 아니니 머지하고 다음 단계 진행하시면서 여유가 되면 다시 한 번 살펴봐주시면 좋을 것 같습니다! 삽질하는 게 더 힘드셨을텐데 고생 많으셨어요 죠스!! 우리 조금만 더 힘내요 💪

2023-01-19 05:28 UTC, merged

2023-01-19 05:51 UTC, park0503 commented
> @park0503
> 
> > 테스트를 작성하는데 RestAssured를 사용한 테스트들은 @nested 어노테이션을 이용해 묶으니 connection refused 에러가 발생하더라구요. 포트 문제인가 싶어 테스트 환경을 RANDOM_PORT로도 수정해 보고 했는데도 해결하지 못해 테스트 메소드들이 조금 난잡하게 배치되어 있는 상황입니다. 이러한 문제가 발생하는 원인이 무엇일까요?
> 
> 흠... RestAssured를 저는 써본 적이 없어서 큰 도움은 안 되는 것 같아 죄송합니다ㅠㅠ (저희는 그냥 간단한 전역 테스트는 WebTestClient로 확인하고 있습니다. 이렇게 쓰시라는 건 아니고!! 그냥 궁금하실까봐ㅎㅎ) 제가 잠깐 돌려봤을 때 @nested를 붙이지 않고 PORT만 RANDOM_PORT로 수정해도 Connection refused가 발생하네요..
> 
> RestAssured 버전도 현재 버전은 5.3.0인데 3.3.0을 쓰고 계시던데, 빌드 시에 충돌이 나서 이전 버전을 쓰신걸까요? 추가로 docs를 잠시 봤는데 이런 주의 사항도 있었네요😳
> 
> > You should place rest-assured before the JUnit dependency declaration in your pom.xml / build.gradle in order to make sure that the correct version of Hamcrest is used.
> 
> 해당 이슈는 주요 문제는 아니니 머지하고 다음 단계 진행하시면서 여유가 되면 다시 한 번 살펴봐주시면 좋을 것 같습니다! 삽질하는 게 더 힘드셨을텐데 고생 많으셨어요 죠스!! 우리 조금만 더 힘내요 💪

넵 말씀하신대로 3단계 요구사항 마무리 한 뒤 버전 최신화 및 의존성 순서 변경 등 조치를 취해 봐야 될 것 같습니다.
감사합니다!!