[huny.jeong] 방탈출 인증 관리 1, 2단계
2023newkrew/spring-roomesacpe-auth-kakao pull request #27
Opened 2023-01-18 00:53 UTC by person003333

이전 과제들은 직접 개발하는게 많았는데 이번 과제는 인증을 추가하는 과제인지 베이스 코드가 많이 주어졌네요.
과제에 알맞게 코드를 추가해보았습니다.

## 토큰 발급 API
로그인시 username과 password를 비교하고 db에서 username으로 검색해서 memeber의 정보를 가져온 다음 password를 비교하며 일치하면 토큰을 발급하도록 하였습니다.

## 내 정보 조회
토큰에 memeber의 id를 저장하고 이를 통해서 가져와 자기정보 조회하도록 하였습니다.

## 예약하기, 예약취소 개선
예약하기, 예약취소 하기에서 HandlerMethodArgumentResolver를 활용하여 만든 @AuthenticationPrincipal 어노테이션을 사용하여 로그인 토큰을 확인하도록 하여 로그인 하여야만 가능하도록 하였습니다.
예약 취소 시에는 예약정보의 예약자 아이디와 로그인 아이디가 일치 할 때만  삭제 가능하도록 하였습니다.

2023-01-18 06:54 UTC, teddy-ready requested changes
소스 한번 정리하고 가겠습니다~
인프라스트럭처 등 패키지로 유추해 보아 DDD 컨셉으로 원하시는 것 같아서 아래와 같이 해보겠습니다

com.nextstep.configurations
> 모든 부트를 위한 설정 파일
com.nextstep.interfaces
> 프리젠테이션 레이어
com.nextstep.domains
> 도메인 레이어
com.nextstep.applications
> 크로스 도메인을 위한 레이어
com.nextstep.infrastructures
> 어떤 레이어에서도 사용할수 있는 인프라 레이어 

인프라스트럭처 레이어에 정의된 객체는 어떤 레이어에서도 사용가능합니다.
인터페이스 -> 도메인
인터페이스 -> 애플리케이션 
애플리케이션 -> 도메인


이렇게 정리를 해보자면,

com.nextstep.configurations
> WebMvcConfiguration.java

com.nextstep.interfaces
> AuthorizationException.java
> ExceptionHandlers.java

com.nextstep.interfaces.auth
> AuthController.java
com.nextstep.interfaces.member
> MemberController.java
com.nextstep.interfaces.reservation
> ReservationController.java
com.nextstep.interfaces.reservation.dto
> ReservationRequest.java

com.nextstep.domains
com.nextstep.domains.member
> Member.java
> MemberService.java
> MemberDao.java
=> 모든 응답은 Member 형태로 반환하여 바운더리 형성

com.nextstep.domains.reservation
> Reservation.java
> ReservationService.java
> ReservationDao.java

com.nextstep.applications

com.nextstep.infrastructures
com.nextstep.infrastructures.web
> AuthenticationPrincipal.java
> LoginMember.java 
=> UserContextHoler.java 라는 명명도 좋을 것 같습니다.
> AuthorizationExtractor.java
> AuthenticationPrincipalArgumentResolver.java 
> JwtTokenProvider.java
=> 위의 2개 객체에 있는 컨포넌트 어노테이션을 빼고 WebMvcConfiguration.java 에서 빈으로 정의해서 명시적으로 인프라에 있는 리졸버를 로딩

2023-01-18 06:54 UTC, teddy-ready commented on src/main/java/nextstep/reservation/ReservationController.java
>          return ResponseEntity.created(URI.create("/reservations/" + id)).build();
서비스에서 웹 플랫폼 성격이 있는 LogInMember 객체를 그대로 받으면, 의존관계가 생깁니다.
이부분을 해제하기 위해서 LogInMember 값 중에 필요한 값만 풀어서 전달 부탁드립니다.

2023-01-18 06:54 UTC, teddy-ready commented on src/main/java/nextstep/reservation/ReservationService.java
>          Schedule schedule = scheduleDao.findById(reservationRequest.getScheduleId());
서비스에서 웹 플랫폼 성격이 있는 LogInMember 객체를 그대로 받으면, 의존관계가 생깁니다.
이부분을 해제하기 위해서 LogInMember 값 중에 필요한 값만 풀어서 전달 부탁드립니다.
ID 만 받아서 서비스를 구현하면 서비스 객체의 메소드를 더 유연하게 사용할 수 있습니다

2023-01-18 09:08 UTC, person003333 commented
피드백 해주신대로 패키지 구조를 변경하였고,
컨포넌트 어노테이션을 빼고 WebMvcConfiguration.java 에서 빈으로 정의해서 명시적으로 인프라에 있는 리졸버를 로딩 하였습니다.
또 의존관계가 생기는 부분도 수정하였습니다.

패키지 구조의 경우 어떻게 작성해야 하는지 궁금했는데 자세히 알려주셔서 정말 감사합니다.

그런데, 이번 과제의 경우 기존에 작성되있던 베이스가 많았고 일부분만 수정하여 pull request에 모든 파일이 들어가 있지 않아서 
바꾸지 않았던 패키지들의 구조를 어떻게 작성하면 좋을지 궁금합니다.
Schedule 이나 Theme의 경우 피드백해주신 Reservation 과 Memeber 의 구조와 비슷하여서 같이 정리를 하였는데

com.nextstep.support 패키지에 있는 Exception 클래스들의 경우 어떻게 정리하는게 맞는지 궁금하여 문의드립니다.

2023-01-19 06:33 UTC, teddy-ready approved these changes
com.nextstep.support 패키지에 있는 Exception 객체들은 interfaces 패키지 밑에 두시면 좋을 것 같습니다~

2023-01-19 06:33 UTC, merged