[sienna.o] 방탈출 인증 관리 1, 2단계
2023newkrew/spring-roomesacpe-auth-kakao pull request #30
Opened 2023-01-18 02:34 UTC by binimini

안녕하세요 맷! 아직 저번주 미션이 마무리가 안됐지만 분량이 많아서 천천히 보시라고 PR을 미리 올려놓습니다ㅎㅎ

이번 미션은 기존 방탈출 예약에서 인증 관련 기능을 구현하기였습니다!
예약 생성, 조회와 같은 기능은 기존과 동일하지만, [제공해주는 코드](https://github.com/next-step/spring-roomesacpe-auth-kakao/tree/main)를 사용해서 스키마와 엔티티의 차이가 존재합니다.
<details>
<summary> 달라진 스키마</summary>

```sql
CREATE TABLE reservation
(
    id          bigint      not null auto_increment,
    schedule_id bigint      not null,
    member_id   bigint      not null, -- 이 부분은 제공해주신 코드에서 제가 변경했습니다!
    primary key (id)
);

CREATE TABLE theme
(
    id    bigint       not null auto_increment,
    name  varchar(20)  not null,
    desc  varchar(255) not null,
    price int          not null,
    primary key (id)
);

CREATE TABLE schedule
(
    id       bigint not null auto_increment,
    theme_id bigint not null,
    date     date   not null,
    time     time   not null,
    primary key (id)
);

CREATE TABLE member
(
    id       bigint      not null auto_increment,
    username varchar(20) not null,
    password varchar(20) not null,
    name     varchar(20) not null,
    phone    varchar(20) not null,
    primary key (id)
);
```
</details>

### 구현 내용
- 인증 구현
  - 토큰 발급하는 API 구현
  - 내 정보 조회 API 구현
- 기존 API의 수정
  - 비로그인 사용자는 예약이 불가능하다.
  - 자신의 예약이 아닌 경우 예약 취소가 불가능하다.

기존 (제공해주는) 코드를 리팩토링하는 부분도 포함되어있습니다.

### 질문
1. 인증 정보(토큰)을 사용해서 해당 사용자 정보를 사용하는 기능 구현시 두 가지 방식을 고려했습니다.
      - ArgumentResolver 내에서 서비스(MemberService)를 사용해서 멤버를 조회해 객체로 반환
      - 토큰 파싱으로 id와 같은 식별 정보만 반환, 이후에 별도로 사용자(멤버) 조회

     초기에는 첫 번째 방식으로 구현했지만,  인증시 불필요한 DB에 대한 접근이 발생할 수 있어 
  사용자(멤버) 조회 로직은 컨트롤러 이후의 서비스가 갖도록 수정했습니다. (두 번째 방식으로 변경)
  첫 번째 방식과 같이 인증시 정보를 조회하는 방식도 많이 사용하나요? (사용한다면 어떤 경우에 많이 사용하나요?)

2. 컨트롤러가 서비스를 사용하고, 각각의 서비스가 맡은 엔티티 관련 로직을 수행하도록 구성하니
메인 컨트롤러에서 많은 서비스를 사용하게 되었는데, 이럴 경우에 사용하는 서비스를 줄이기 위해서
특정 엔티티가 상하관계를 가지는 경우에 (Schedule이 Theme를 포함) 하위 엔티티 로직까지 책임을 가지는 게 나을까요?
(`ScheduleService -> ScheduleDao, ThemeService -> ThemeDao` /  `ScheduleService -> ScheduleDao, ThemeDao`)
   
     ```java
    @RestController
    @RequestMapping("/reservations")
    public class ReservationController {
        
        private final ReservationService reservationService;
        private final AuthService authService;
        private final MemberService memberService;
        private final ScheduleService scheduleService;
        private final ThemeService themeService;
        // ...
    }
     ```

---
스프링 프로젝트가 되니 코드 분량이 굉장히 많아지네요 😮 💦
급하지 않으니 맷 편한 시간에 천천히 봐주시면 될 것 같습니다ㅎㅎ
오늘도 미리 리뷰 감사합니다! 😺

2023-01-26 01:30 UTC, matt-jylee requested changes
고생하셨습니다. 
점점 작성해야 할 코드가 증가하고, 신경써야 할 부분이 많아지고 있습니다.

기존에 리뷰했던 내용들과 어제 리뷰한 내용들을 반영해서 코드 내용에 집중해 보면 좋겠습니다!

2023-01-31 01:54 UTC, binimini commented
여러 일정과 휴일로 미션 진행 사항이 많이 늦어졌네요 🥲
말씀해주신 리뷰 내용 참고해서 수정했습니다!

2023-01-31 11:28 UTC, matt-jylee approved these changes
많은 부분 리뷰 드린대로 잘 해결하신것 같습니다.

고생하셨습니다!

2023-01-31 11:28 UTC, matt-jylee commented on src/main/java/nextstep/auth/AuthController.java
> +    }
이부분 이야기 하기 킵

2023-01-31 11:29 UTC, merged