[gray.ts] 방탈출 인증 관리 1, 2단계
2023newkrew/spring-roomesacpe-auth-kakao pull request #34
Opened 2023-01-18 04:52 UTC by abcworld123

에디 안녕하세요 그레이입니다.
이번주는 인증 관련 로직이 추가되었습니다.
이번에도 잘 부탁드립니다.

2023-01-19 02:31 UTC, abcworld123 commented
db쪽에 저번주에 말씀해주신 리뷰를 반영할 부분이 많이 보이는 것 같습니다. 3단계에서 적용하겠습니다.

별도로 한가지 궁금한 부분이 있는데,
기본 제공된 코드에서 `Schedule`이라는 테이블을 사용했던데, 제가 느끼기에는 현재 프로젝트 수준에서는 reservation 하나로 합쳐도 될 것 같다는 생각이 들었습니다. 에디의 의견은 어떠신지 궁금합니다. 혹시 `Schedule`을 분리함으로써 얻는 이득이 있을까요?

2023-01-19 03:57 UTC, eddy-oum commented on src/main/java/nextstep/auth/AuthController.java
> +@RestController
Q. RestController와 Controller의 차이점은 무엇일까요?

2023-01-19 04:30 UTC, abcworld123 commented on src/main/java/nextstep/auth/AuthController.java
> +@RestController
저번에 찾아보기로는 RestController는 Controller에 추가적으로 dto 자체를 리턴해도 json 형식으로 변환되며, 다만 세부적인 response 조작을 위해서는 ResponseEntity를 여전히 사용해야 하는 것으로 알고 있습니다. 혹시 제가 놓친 더 중요한 부분이 있을까요?

2023-01-19 06:05 UTC, eddy-oum requested changes

2023-01-19 06:05 UTC, eddy-oum commented on src/main/java/nextstep/auth/AuthController.java
> +        return ResponseEntity.ok().body(tokenResponse);
이 부분은 사실
```java
public TokenResponse login(..) {
    return tokenReponse;
}
```
만 해줘도 됩니다.

2023-01-19 06:05 UTC, eddy-oum commented on src/main/java/nextstep/auth/AuthorizationExtractor.java
> +    public static final String AUTHORIZATION = "Authorization";
org.springframework.http.HttpHeaders 처럼
HttpHeaders.AUTHORIZATION 같은 상수를 제공하는 패키지도 많이 있습니다.

2023-01-19 06:05 UTC, eddy-oum commented on src/main/java/nextstep/member/MemberController.java
> +    public ResponseEntity<MemberResponse> me(@AuthenticationPrincipal HttpServletRequest request) {
HttpServletRequest는 ```@AuthenticationPrincipal``` 어노테이션이 없더라도 컨트롤러에서 접근이 가능해요.

그리고 ReservationController에서 해주신 것처럼 ```@AuthenticationPrincipal Member member```로 Member 객체를 바로 사용해주시면 좋을 것 같아요.

2023-01-19 06:05 UTC, eddy-oum commented on src/main/java/nextstep/theme/ThemeController.java
> +    public ResponseEntity deleteTheme(@PathVariable Long id) {
nit: 이 경우에는 ResponseEntity is a raw type 관련된 경고가 발생해서, ```ResponseEntity<Void>``` 가 더 좋은 것 같아요.

2023-01-19 06:05 UTC, eddy-oum commented on src/main/java/nextstep/reservation/ReservationController.java
>          reservationService.deleteById(id);
reservationService의 deleteById는 dao / repository에 어울리는 메소드인 것 같아요.

저희의 방탈출 "비즈니스"를 고려하면 reservertaionService.cancelReservation(Member m, Long reserveId);
같은 메소드의 형태가 가능할 것 같아요.

그럼
```java
        if (!reservation.getName().equals(member.getUsername())) {
            throw new ReservationForbiddenException("예약당사자만 예약을 삭제할 수 있습니다.");
        }
```
라는 비즈니스로직은 자연스럽게 reservationService에 들어가게 됩니다.

2023-01-19 06:05 UTC, eddy-oum commented on src/main/java/nextstep/reservation/ReservationResponse.java
> +    private Long scheduleId;
Long scheduleId 대신에 schedule 값 자체를 갖고 있어도 좋을 것 같습니다.

2023-01-19 06:05 UTC, eddy-oum commented on src/main/java/nextstep/member/MemberResponse.java
> +    private String password;
nit: https가 적용되면 payload에 비밀번호가 포함되어도 괜찮겠지만, 멤버 생성 응답으로 password는 전달해주지 않는 것이 더 안전할 것 같아요.

2023-01-19 06:05 UTC, eddy-oum commented on src/main/java/nextstep/reservation/ReservationController.java
>          Long id = reservationService.create(reservationRequest);
deleteById와 비슷하게, reservationService.reserve(member, req) 같은 메소드가 더 비즈니스로직을 잘 드러내는 것 같아요.
검증 로직도 마찬가지로 자연스레 서비스레이어로 가게 될 것 같습니다.

2023-01-19 06:05 UTC, eddy-oum commented on src/main/java/nextstep/reservation/ReservationController.java
>          Long id = reservationService.create(reservationRequest);
+
reservationRequest.getName()이 null일 수도 있을 것 같아요.
@Valid 등을 이용한 dto검증이 되면 더 좋겠습니다.

```java
member.getUsername().equals(req.getName())
```
처럼 null이 아닌 것이 확실한 필드를 앞에 두는 방법도 존재합니다.
다만 이 방법의 경우 null 인 것을 명시적으로 처리안하고, 숨기기떄문에 별로라는 의견도 많습니다.

2023-01-19 06:07 UTC, eddy-oum commented
고생하셨습니다. 생소하실 것 같은 @AuthenticationPrincipal 관련된 클래스들을 잘 적용해주셨네요.

예약자 명 확인 관련 로직은 저희의 비즈니스 로직에 해당한다는 생각이 들어요. 관련 로직을 서비스 로직으로 옮겨주시면 좋을 것 같아요.

2023-01-19 06:09 UTC, eddy-oum commented on src/main/java/nextstep/reservation/ReservationController.java
>          reservationService.deleteById(id);
+)
getter 도 지양하자는 관점하에서 보면,
```reservation.reservedBy(Member) : Boolean```
같은 메소드가 나와도 좋을 것 같아요.

2023-01-19 06:17 UTC, eddy-oum commented
> db쪽에 저번주에 말씀해주신 리뷰를 반영할 부분이 많이 보이는 것 같습니다. 3단계에서 적용하겠습니다.
> 
> 별도로 한가지 궁금한 부분이 있는데, 기본 제공된 코드에서 `Schedule`이라는 테이블을 사용했던데, 제가 느끼기에는 현재 프로젝트 수준에서는 reservation 하나로 합쳐도 될 것 같다는 생각이 들었습니다. 에디의 의견은 어떠신지 궁금합니다. 혹시 `Schedule`을 분리함으로써 얻는 이득이 있을까요?

정규화(분리)를 할 것인지 반정규화(합치기)를 할 것인지는 성능 및 다른 여러 요구사항에 따라 달라지고, 정답은 없다고 생각합니다.
다만 저는 이번에는 스케줄과 예약이 따로 존재하는 것이 자연스럽다라고 생각을 했습니다.

일반적인 예약은 가능한 스케줄중 하나를 고르고나서, 예약확정을 하는 방식이기 때문에요.
스케줄은 예약과 별도로 따로 존재해야한다고 생각을 했습니다.

2023-01-19 06:19 UTC, eddy-oum commented on src/main/java/nextstep/auth/AuthController.java
> +@RestController
맞습니다. 👍

다만 dto 자체를 리턴해도 json으로 변환되는 역할을 하는 annotation이 @ResponseBody 어노테이션이고,
@RestController는 
```java
/**
 * A convenience annotation that is itself annotated with
 * {@link Controller @Controller} and {@link ResponseBody @ResponseBody}.
*/
```
임을 TMI로 알려드리고 싶었습니다.

2023-01-25 07:38 UTC, eddy-oum approved these changes

2023-01-25 07:38 UTC, eddy-oum commented on src/main/java/nextstep/auth/AuthenticationPrincipalArgumentResolver.java
> +    private MemberService memberService;
nit : 필드레벨 autowired 보다는 생성자 주입을 애용해주시면 좋겠습니다.



> So what should you use?
> 
> We usually advise people to use constructor injection for all mandatory collaborators and setter injection for all other properties. Again, constructor injection ensures all mandatory properties have been satisfied, and it is simply not possible to instantiate an object in an invalid state (not having passed its collaborators). In other words, when using constructor injection you do not have to use a dedicated mechanism to ensure required properties are set (other than normal Java mechanisms).

https://spring.io/blog/2007/07/11/setter-injection-versus-constructor-injection-and-the-use-of-required
에서 발췌

추가적으로 생성자를 이용하면 테스트할 때 생성자에 임의의 모킹된 구현체를 넣어줘서 스프링 context와 무관하게, 더 간단하게 테스트할 수 있다라는 장점도 있습니다.

2023-01-25 07:38 UTC, eddy-oum commented on src/main/resources/schema.sql
> +CREATE INDEX ON member(username);
create table의 username에 UNIQUE 제약조건을 걸어주시면 좋을 것 같아요.
그러면 자동으로 index까지 생성됩니다.

2023-01-25 07:39 UTC, eddy-oum commented
고생하셨습니다 :)

2023-01-25 07:39 UTC, merged

2023-01-25 07:51 UTC, abcworld123 commented on src/main/java/nextstep/auth/AuthenticationPrincipalArgumentResolver.java
> +    private MemberService memberService;
와 전혀 몰랐습니다... 좋은 정보 감사합니다!!