[jayden.v] 인증 과제 step1 제출
2023newkrew/spring-roomesacpe-auth-kakao pull request #37
Opened 2023-01-18 07:08 UTC by Tarakyu

## 구현사항
JWT를 기반으로 로그인을 하고 Interceptor로 검증한 뒤 ArgumentResolver로 userId를 넘기는 것을 위주로 구현하였습니다.

## 아쉬운 점
- 평소에 인증을 구현할 때 Spring Security를 주로 이용하였는데, 이번에는 그것 없이 인증을 구현해보니 되게 어려웠습니다. 
```java
//WebMvcConfiguration
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(new LoginInterceptor(jwtTokenProvider, HttpMethod.POST)).addPathPatterns("/reservations/**");
        registry.addInterceptor(new LoginInterceptor(jwtTokenProvider, HttpMethod.DELETE)).addPathPatterns("/reservations/**");
    }
```
메서드에 따라 필터링을 다르게 하기 위해 위와 같이 interceptor를 여러 개 생성하였는데 저렇게 각각의 Interceptor에 `jwtTokenProvider`를 넣어주는 게 좋은 패턴같지는 않아서 많이 고민되었습니다.
- 평소에는 `SecurityContextHolder`에 userId를 보관해두어 쉽게 구현했던 부분을 직접 구현하려 해보니 굉장히 어려웠습니다. `SecurityContextHolder`의 구현이 어떻게 되어있는지도 공부해봐야 할 것 같습니다.

## disclaimer
- 예약을 삭제할 때 자신의 예약인지 검증을 하는데, 이 때 이름을 기준으로 이를 확인하기에 동명이인의 예약이 삭제 가능합니다. 디폴트로 설계된 스키마를 고려해 이러한 스펙으로 구현하였는데, 의문은 남았지만 학습주제와 관련이 없다고 생각해 일단 그대로 두었습니다..

2023-01-19 06:10 UTC, gogyzzz requested changes

2023-01-19 06:10 UTC, gogyzzz commented on src/main/java/nextstep/theme/ThemeController.java
>  public class ThemeController {
createTheme 의 ThemeRequest 에 음수 price 가 들어갈 때 validation이 필요해보입니다~

2023-01-19 06:10 UTC, gogyzzz commented on src/main/java/nextstep/member/MemberController.java
>      @PostMapping
Controller 공통적으로 해당되는 내용인데요, POST를 통해 body를 전달할 때 정해진 형식과 다르게 넣으면
Dao 의 QueryForObject 에서 값을 못 가져와 EmptyResultDataAccessException이 발생하더라구요
이전 프로젝트에서 구현했던 ControllerAdvice 를 적용하는게 어떨까 싶습니다

2023-01-19 06:10 UTC, gogyzzz commented on src/main/java/nextstep/schedule/ScheduleController.java
>          this.scheduleService = scheduleService;
createSchedule에 날짜 형식을 아무렇게나 넣어도 들어가기는 하더라구요
날짜 형식 validation이 필요해보입니다~

2023-01-19 06:10 UTC, gogyzzz commented on src/main/java/nextstep/auth/AuthController.java
> +    @PostMapping("/token")
아래처럼 member 생성 후

<img width="494" alt="image" src="https://user-images.githubusercontent.com/8141431/213368370-700c1dde-1212-4b18-af3b-0c63a3dbd78a.png">

login 시도를 해봤는데요, 아래처럼 500 에러가 뜹니다.

<img width="522" alt="image" src="https://user-images.githubusercontent.com/8141431/213368396-dbc608d2-9bc5-437c-b958-d65da8437d5a.png">

제가 재현을 잘 못하고 있는 것 같은데... 어떻게 해야 로그인 할 수 있나요?

2023-01-19 06:11 UTC, gogyzzz commented
AuthE2E에 Theme 관련 테스트가 같이 들어있는 이유가 궁금합니다~

2023-01-19 06:11 UTC, gogyzzz commented
ThemeE2ETest 의 주석을 제거해도 되면 제거하는게 좋겠어요~

2023-01-19 06:13 UTC, gogyzzz commented
ScheduleController의 메서드 중 이름에 Reservations 가 들어간 게 있습니다. 혹시 의도적인 네이밍일까요
- showReservations
- deleteReservations

2023-01-19 06:14 UTC, gogyzzz commented
ReservationService의 findAllByThemeIdAndDate 메서드를 보면 결과가 없을 시 NPE 를 던지는데요,
어차피 내부의 findAllByThemeIdAndDate 에서 빈 리스트를 리턴 할테니까 예외처리 부분을 없애도 될 것 같습니다~

2023-01-19 06:15 UTC, gogyzzz commented
모든 도메인 Service 의 리턴 타입 관련해서 말인데요, 
null을 리턴하는 메서드들의 리턴 타입을 Optional로 하고, orElse 등을 통해 예외처리를 하는게 좋을 것 같습니다~

2023-01-19 06:51 UTC, gogyzzz commented
httpMethod 별 LoginInterceptor 를 쓰는 부분 말인데요, 
저도 잘 몰라서 구글링을 해봤어요 
https://stackoverflow.com/a/68326759 를 보면 NeedLogin 이라는 Annotation을 붙여서 메서드 별로 로그인 필요여부 표시하더라구요
POST 나 DELETE 가 물론 데이터를 조작하는 성격의 http method 니까 그냥 http method 별로 인터셉터를 붙여도 될 것 같긴 한데 아예 endpoint 마다 로그인 검사를 하는 것도 좋아보여요

2023-01-25 08:52 UTC, Tarakyu commented
> AuthE2ETest에 Theme 관련 테스트가 같이 들어있는 이유가 궁금합니다~

> ThemeE2ETest 의 주석을 제거해도 되면 제거하는게 좋겠어요~

> ScheduleController의 메서드 중 이름에 Reservations 가 들어간 게 있습니다. 혹시 의도적인 네이밍일까요

지난 과제(예약과 테마 관리)의 구현 결과가 각자 달라서 진행이 어려울 수 있으니 강사님이 디폴트 코드를 제공해주셨는데, 그쪽 코드는 과제 목표가 아니어서 신경을 안 썼는데 이런 문제점들이 있었네요... 😓 말씀해주신 부분들 수정해두었습니다! 

<hr>

> 모든 도메인 Service 의 리턴 타입 관련해서 말인데요,
null을 리턴하는 메서드들의 리턴 타입을 Optional로 하고, orElseGet 등을 통해 예외처리를 하는게 좋을 것 같습니다~

미리 구현되어있던 예외처리 부분들도 제 마음에 안 들었었는데 이참에 제 스타일대로 다 바꾸었습니다.
<hr>

> NeedLogin 이라는 Annotation을 붙여서 메서드 별로 로그인 필요여부 표시하더라구요

저도 `LoginInterceptor`를 이용하는 방법에서는 어떻게 엔드포인트별로 접근을 제어할 수 있나 궁금했는데, 말씀해주신대로 어노테이션을 이용하는 방법이 가장 깔끔하게 해결하는 것 같네요! 과제에도 바로 적용해보았습니다.
[refactor: LoginInterceptor를 메서드 별로 분리하지 않고 어노테이션을 이용해 엔드포인트별로 적용](https://github.com/next-step/spring-roomesacpe-auth-kakao/pull/37/commits/aeaad15ebec05dc4b28e2ffc8b1f752f754a4ad2)

좋은 리뷰 항상 감사드립니다!

2023-01-25 08:52 UTC, Tarakyu commented on src/main/java/nextstep/auth/AuthController.java
> +    @PostMapping("/token")
디폴트 코드가 자바 11 이상에서 작동을 안 하게 작성이 되어있었네요.. 호환성 보장하도록 수정했습니다!

2023-01-25 08:52 UTC, Tarakyu commented on src/main/java/nextstep/schedule/ScheduleController.java
>          this.scheduleService = scheduleService;
이 곳에도 validation 추가하였습니다!

2023-01-25 08:52 UTC, Tarakyu commented on src/main/java/nextstep/member/MemberController.java
>      @PostMapping
Controller Advice를 추가하여 예외처리 하였습니다!

2023-01-25 08:52 UTC, Tarakyu commented on src/main/java/nextstep/theme/ThemeController.java
>  public class ThemeController {
validation 추가했습니다!

2023-01-26 02:19 UTC, merged