[jerrie.choi] 방탈출 인증 관리 Step3
2023newkrew/spring-roomesacpe-auth-kakao pull request #41
Opened 2023-01-18 07:35 UTC by CHOIJXWXN

안녕하세요 요한,
이번 리뷰도 잘 부탁드립니다 🙇‍♀️

이번 단계의 미션에서 막혔던 부분이 있어 여쭤보고 싶은 게 있습니다.

Interceptor에서 개인적으로 Service를 쓰지 않기 위해
(토큰으로 유저네임을 추출하고 유저네임으로 멤버를 조회하여 역할을 받아오지 않기 위해)
토큰에 바로 역할을 저장해두었습니다.
**1 . 토큰에 역할을 저장해두어도 괜찮은 것인지 일차적으로 궁금합니다.**

일단 저는 JwtTokenProvider의 createToken 메서드를 수정해서, 저장해두고 사용하였는데요,
꺼내어 쓸 때 enum 타입이 아닌 String으로 반환이 되더라구요.
JwtTokenProvider의 getRole 메서드에서,
`Jwts.parser().setSigningKey(secretKey).parseClaimsJws(token).getBody().get(AUTHORITIES_KEY, MemberRole.class);`
혹은
```(MemberRole) Jwts.parser().setSigningKey(secretKey).parseClaimsJws(token).getBody().get(AUTHORITIES_KEY);```
를 반환하게 되면 에러가 발생했습니다.
토큰 안에 저장되어 있는 게 MemberRole.ADMIN이 아닌 "ADMIN" 문자열로 보였습니다.
그래서 어쩔 수 없이 toString을 이용해서 String을 반환하고 Interceptor에서는 MemberRole.ADMIN.toString()과 비교하여 이 토큰을 가진 유저가 관리자인지 일반 회원인지 구분했습니다.
**2 . 이런 문제를 어떻게 하면 더 잘 해결할 수 있을까요?**

설날 잘 보내시고, 새해 복 많이 받으세요!
요한이 남겨주시는 코멘트가 정말 많은 도움이 됩니다. 늘 감사합니다 🫡

2023-01-19 01:17 UTC, leeyohan93 requested changes
피드백을 잘 적용하고 이번 단계 진행해주셨네요 👍 👍 

질문에 대한 답변은 코멘트 작성해두었으니 확인 부탁드려요 :)

2023-01-19 01:17 UTC, leeyohan93 commented on src/main/java/nextstep/auth/JwtTokenProvider.java
> +        claims.put(AUTHORITIES_KEY, role);
> 토큰에 역할을 저장해두어도 괜찮은 것인지 일차적으로 궁금합니다.

JWT 토큰은 전송 Payload까지 암호화하지 않기 때문에 민감정보를 저장하지 않아야 한다고 생각합니다.
역할이 민감정보는 아니지만 토큰이 탈취됬을 때를 고려해서 권장하지는 않을 것 같아요!
~~만약 어드민 권한의 토큰이 탈취된다면, 이 토큰을 이용해 마음대로 테마를 변경해버릴 수 있지 않을까요?~~
위 예시보다는 어드민 권한이 유저 권한으로 바뀌었을 때를 가정해보는 것이 괜찮을 것 같네요! :)

2023-01-19 01:17 UTC, leeyohan93 commented on src/main/java/nextstep/auth/JwtTokenProvider.java
> +    }
> 2 . 이런 문제를 어떻게 하면 더 잘 해결할 수 있을까요?

캐스팅에 대한 질문을 주신 것 같은데요! 
Enum에 대한 타입 캐스팅이라면 아래와 같이 변경해보는건 어떨까요? :)

```suggestion
    public MemberRole getRole(String token) {
        String s = Jwts.parser()
                .setSigningKey(secretKey)
                .parseClaimsJws(token)
                .getBody()
                .get(AUTHORITIES_KEY)
                .toString();
        
        return MemberRole.valueOf(s);
    }
```

2023-01-19 01:17 UTC, leeyohan93 commented on src/main/java/nextstep/member/Member.java
> +    }
기본 값을 설정해주고 변경하기 보다는, 생성자를 통해서 받을 수 있도록 설정해주는건 어떨까요? :)

2023-01-19 01:17 UTC, leeyohan93 commented on src/main/java/nextstep/support/GlobalExceptionHandler.java
> +    }
적절한 예외 응답 👍 👍

2023-01-19 01:17 UTC, leeyohan93 commented on src/main/java/nextstep/ui/interceptor/AdminInterceptor.java
> +        if (!jwtTokenProvider.getRole(token).equals(MemberRole.ADMIN.toString())) throw new ForbiddenException();
만약 등록되지 않은 유저 아이디와 관리자 Role을 가진 토큰으로 요청이 오면 예외가 발생할까요? 🤔 

현재 AuthenticationPrincipalArgumentResolver 에서는 인증을, AdminInterceptor 에서는 인가를 처리하고 있는데요.
Interceptor 에서 인증/인가를 함께 처리하고 AuthenticationPrincipalArgumentResolver 에서는 인증/인가된 id를 로그인된 멤버 인자로 변경해주는 역할을 담당하도록 변경해보는 것은 어떨까요? :)

2023-01-19 01:53 UTC, CHOIJXWXN commented on src/main/java/nextstep/auth/JwtTokenProvider.java
> +        claims.put(AUTHORITIES_KEY, role);
그렇다면 Interceptor에서 토큰으로부터 유저네임을 추출해서 해당 유저네임으로 디비 조회 후 역할이 어드민인지 확인하는 방법이 최선일까요?

2023-01-19 02:05 UTC, leeyohan93 commented on src/main/java/nextstep/auth/JwtTokenProvider.java
> +        claims.put(AUTHORITIES_KEY, role);
최선이라기 보다는 상황에 맞춰 구현해야한다는 것을 고려하시는게 좋을 것 같아요 🤔 

요청이 많아져 부하가 걸린다면, 구현해주신 것처럼 디비를 조회하는 대신 jwt 토큰에 역할을 넣어야될 수 있습니다!
대신 jwt 토큰의 리프레시나 유효기간에 신경을 써야겠지요.

실시간으로 변경이 반영되는 것이 민감하다면 DB를 조회하는 것이 또 적절할 수 있습니다!

여러 상황을 고려해보시고 그때에 맞는 최선을 고려해보시면 좋을 것 같아요 :)

2023-01-19 06:22 UTC, CHOIJXWXN commented
요한이 제안해주신 대로 Interceptor에 인증/인가를 모두 처리하고
ArgumentResolver에서는 LoginMember로 바꾸어 반환시키도록 바꾸었습니다.

로그인 인터셉터에서는 헤더 유무 / 토큰 만료 / 회원 가입 여부를 확인을 하고,
어드민 인터셉터에서는 로그인 인터셉터를 거쳐서 전달되는 회원 역할 정보가 어드민인지 판별합니다.
이후 ArgumentResolver에서는 유저네임을 통해 LoginMember를 반환하도록 했습니다.

이 셋이 서로 HttpServletResponse를 통해 데이터를 주고 받는 게 좋은 방법인지 잘 모르겠습니다.
혹시 더 좋은 방법이 있다면 알려주세요!

아 이렇게 구조를 바꾸니 토큰에 역할을 저장할 필요가 없어져서 삭제했습니다 👍👍

2023-01-25 02:06 UTC, leeyohan93 approved these changes
안녕하세요 제리~
피드백을 잘 반영해주셨네요 👍 
질문 주신 부분에 대해서는 코멘트 남겨두었습니 확인 부탁드려요 :)
이번 단계도 고생 많으셨습니다 😄

2023-01-25 02:06 UTC, leeyohan93 commented on src/main/java/nextstep/ui/interceptor/AdminInterceptor.java
> +        if (!role.equals(MemberRole.ADMIN)) throw new ForbiddenException();
enum 클래스는 equals 대신 아래와 같이 비교가 가능합니다 :)

```suggestion
        if (role != MemberRole.ADMIN) throw new ForbiddenException();
```

2023-01-25 02:06 UTC, leeyohan93 commented on src/main/java/nextstep/ui/interceptor/AdminInterceptor.java
> +public class AdminInterceptor extends HandlerInterceptorAdapter {
각 역할에 따라 인터셉터를 나누어주셨군요! 👍 👍 
좋은 접근 방법인 것 같습니다 :)

2023-01-25 02:06 UTC, leeyohan93 commented on src/main/java/nextstep/config/WebMvcConfiguration.java
> +                .addPathPatterns("/admin/**");
여러 개의 인터셉터를 등록한다면 순서를 명시적으로 표시해주시는 것이 좋습니다!

```suggestion
        registry.addInterceptor(new LoginInterceptor(loginService))
                .order(1)
                .excludePathPatterns("/members", "/login/token");
        registry.addInterceptor(new AdminInterceptor())
                .order(2)
                .addPathPatterns("/admin/**");
```

2023-01-25 02:06 UTC, leeyohan93 commented on src/main/java/nextstep/ui/interceptor/LoginInterceptor.java
> +        return super.preHandle(request, response, handler);
> 로그인 인터셉터에서는 헤더 유무 / 토큰 만료 / 회원 가입 여부를 확인을 하고,
어드민 인터셉터에서는 로그인 인터셉터를 거쳐서 전달되는 회원 역할 정보가 어드민인지 판별합니다.
이후 ArgumentResolver에서는 유저네임을 통해 LoginMember를 반환하도록 했습니다.
이 셋이 서로 HttpServletResponse를 통해 데이터를 주고 받는 게 좋은 방법인지 잘 모르겠습니다.
혹시 더 좋은 방법이 있다면 알려주세요!

관련해서 Spring Security 에서는 로그인 정보를 스레드 로컬을 활용한 SecurityContextHolder를 통해 정보를 저장하고, 사용하는데요! 이 방법이 항상 좋은 방법이라고는 할 수 없을 것 같습니다! 
상황에 따라 적절한 방법을 찾아 사용하면 될 것 같아요 :)

https://docs.spring.io/spring-security/site/docs/4.2.3.RELEASE/reference/htmlsingle/#securitycontextholder-securitycontext-and-authentication-objects

2023-01-25 02:06 UTC, merged