[baker.gus] Step3
2023newkrew/spring-roomesacpe-auth-kakao pull request #43
Opened 2023-01-18 08:08 UTC by jgus52

안녕하세요 nio

오늘 두개나 올리게 되네요

Interceptor로 관리자만 테마 삭제 및 생성할 수 있도록 했습니다.

늘 리뷰 감사드려요

2023-01-18 14:37 UTC, sehan requested changes
interceptor 를 활용해서 admin api 인증과 권한제어를 잘 구현해주셨습니다. 👍
그렇지만 여기서 한발 더 나아가 interceptor 를 더 적극적으로 활용하여 전체 api 인증과 권한제어를 개선해보면 좋을거 같습니다. 

관련해서 코드에 자세한 코멘트를 남겨 두었습니다. 
개선요청 드립니다.

2023-01-18 14:37 UTC, sehan commented on src/main/java/nextstep/support/WebMvcConfig.java
> +                .addPathPatterns("/admin/**");
/admin/** 어드민 관련 api 의 인증은 interceptor 로 처리하고 일반사용자용 api 는 HandlerMethodArgumentResolver 를 활용하여 인증을 처리하고 있습니다.

2가지로 나눌 필요없이 인증이 필요한 모든 api 에 대해 interceptor 방식으로 인증을 처리할 수 있지 않을까요?
사실 HandlerMethodArgumentResolver 는 request 의 context 상에서 매소드의 변수에 값을 할당 해주는 역할입니다. 토큰이 존재하지 않는 다면 null 값을 할당하는 것이 더 적절해 보입니다.  

interceptor 는 인증/권한 체크를 하고 MemberIdArgumentResolver 는 memberId 에 토큰에서 얻은 값을 할당 해주는 역할만 해주는건 어떨까요?

interceptor 가 토큰에서 추출한 memberId, role 을 MemberIdArgumentResolver 까지 전달 하려면 어떻게 해야할 까요? 이 부분에 대해서 고민해면 좋을거 같습니다.

2023-01-19 05:37 UTC, jgus52 commented
request에 id와 role을 전달했는데 적절할까요?

2023-01-19 14:21 UTC, sehan approved these changes
피드백내용 잘 반영해주셨습니다. 👍
권한의 global 한 처리에 대해서는 코드에 코멘트 남겨두었습니다. 
이번 미션은 여기서 merge 하도록 하겠습니다.  
고생하셨습니다.

2023-01-19 14:21 UTC, sehan commented on src/main/java/nextstep/auth/LoginInterceptor.java
> +
인증처리 후 사용자 식별정보를 request attribute 를 활용하여 request scope 에서 사용할 수 있도록 처리한 것도 나쁘지 않은 선택입니다. 

다만, 권한(authorization) 처리부분은 controller 로 넘어가면서 권한체크가 필요한 부분에 인라인으로 삽입하는 방식으로 처리한 부분은 개선이 필요해 보이긴 합니다. 

권한체크도 한곳에서 처리할 수 있도록 url 패턴이나 그외의 방식을 사용하여 구현할 수 도 있을거 같습니다.
이번 step 에서는 활용하지 않았지만 Filter 를 활용하여 인증, 권한 처리 역활들을 분리하여 처리하도록 구성할 수 도 있겠습니다. 
spring security 도 filter chain 으로 이러한 부분들을 구현하고 있습니다.  관련해서 spring secrity 구성을 참고해 보시면 많은 도움이 될거 같습니다.  😊

ref. https://docs.spring.io/spring-security/reference/servlet/architecture.html

2023-01-19 14:21 UTC, sehan commented on src/main/java/nextstep/theme/ThemeService.java
> +        ThemeValidator.checkRole(loginMember);
interceptor 에서 url 패턴매칭으로 처리하던 부분이 사라지면서 부작용이 발생했네요 😊
이번 미션 범위에서는 어쩔수 없는 선택이라고 봐야겠습니다. 
권한처리도 global 하게 처리하는 부분은 이번 미션이 아니더라도 현업에서 많이 사용하게 될부분이라 처리방법을 고민해 보시면 좋겠습니다.

2023-01-19 14:21 UTC, merged