[woogie.pyun] 인증 관리 - Step3
2023newkrew/spring-roomesacpe-auth-kakao pull request #48
Opened 2023-01-18 08:58 UTC by pyun0825

안녕하세요 요한,

Step3 기능까지 추가해서 리펙토링 해봤습니다.

구현하면서 생각했던 내용들 밑에 적어두었습니다!

즐거운 설 연휴 되세요 요한~! 😀

- `member` 테이블에 `role` 컬럼을 추가하고 객체에선 `Role`이라는 enum 클래스를 만들어 필드로 가지게 해 일반 멤버와 관리자 멤버를 나누는 용도로 사용하게 만들었습니다.
- 처음엔 멤버 생성 요청 API request에 `role` 항목을 추가해서 관리자 멤버도 기존 멤버 만드는 API를 활용해 만들 수 있게 했습니다.
- 그런데 step3 프로그래밍 요구사항 `관리자를 등록하도록 하기 보다는 애플리케이션이 동작할 때 관리자는 추가될 수 있도록 한다` 이 애플리케이션 시작할 때 DB를 init 시키면서 admin을 추가하라는 것 같아서 `data.sql`로 관리자를 생성하도록 변경했습니다.
- JWT에도 멤버의 권한을 기록해주기 위해 token 생성시 넘겨주는 인자로 `TokenGenDto` 클래스를 새로 만들어서 활용해 봤습니다.
- 관리자만 할 수 있는 기능으로는 테마, 스케줄 생성, 삭제를 선택했습니다.
- `/admin` api 들을 하나의 별도의 컨트롤러 클래스에 모아둘까 하다가, 테마나 스케줄에 대한 api들이 일부는 `Theme/ScheduleController`에 있고 다른 일부는 `AdminController`에 있는 것이 오히려 보기 더 불편할 것 같아 따로 `AdminController`를 만들지는 않았습니다.
- 피드백해주신 내용 바탕으로 `ArgumentResolver`에서 `LoggedInUser` 클래스의 객체를 만들어 반환하게 만들었습니다.
- 그러다보니 본인 조회와 같은 기능은 추가적으로 Member 객체 쿼리를 다시 해야되긴 했지만 말씀해주신대로 멤버 객체가 더 많은 연관관계를 가지거나 더 복잡해지면 결국 이렇게 하는게 더 좋은 선택인 것 같습니다!
- 바로 `Member` 객체가 필요한 경우 신규 애노테이션과 `ArgumentResolver`를 만들어서 해당 경우는 가공 안한 멤버 객체를 바로 넘겨주게 만들순 있을 거 같습니다! 그런데 이런식으로 `ArgumentResolver`를 많이 등록시키는게 괜찮을지 잘 모르겠어서 구현하진 않았습니다 🫠🫠

2023-01-19 01:37 UTC, leeyohan93 requested changes
이번 단계도 깔끔하게 잘 적용해주셨네요! 👍 👍 

질문에 대한 답변은 코멘트 작성해두었으니 확인 부탁드려요 :)

2023-01-19 01:37 UTC, leeyohan93 commented on src/main/java/nextstep/auth/TokenGenDto.java
> +    private final Role role;
유저 역할이 민감정보는 아니어서 JWT 토큰에 담는 것이 문제가 될 것 같진 않지만, 
어드민 권한이 유저 권한으로 바뀌었을 때를 가정해보면 어떻게 될까요? 🤔

2023-01-19 01:37 UTC, leeyohan93 commented on src/main/java/nextstep/auth/LoggedInMember.java
> +public class LoggedInMember {
로그인 회원 모델 분리 💯

2023-01-19 01:37 UTC, leeyohan93 commented on src/main/java/nextstep/auth/RoleInterceptor.java
> +    }
만약 등록되지 않은 유저 아이디와 관리자 Role을 가진 토큰으로 요청이 오면 예외가 발생할까요? 🤔

현재 AuthenticationPrincipalArgumentResolver 에서는 인증을, AdminInterceptor 에서는 인가를 처리하고 있는데요.
Interceptor 에서 인증/인가를 함께 처리하고 AuthenticationPrincipalArgumentResolver 에서는 인증/인가된 id를 로그인된 멤버 인자로 변경해주는 역할을 담당하도록 변경해보는 것은 어떨까요? :)

2023-01-19 01:37 UTC, leeyohan93 commented on src/main/java/nextstep/auth/AuthenticationPrincipalArgumentResolver.java
> +        return LoggedInMember.from(loggedInMember);
> 바로 Member 객체가 필요한 경우 신규 애노테이션과 ArgumentResolver를 만들어서 해당 경우는 가공 안한 멤버 객체를 바로 넘겨주게 만들순 있을 거 같습니다! 그런데 이런식으로 ArgumentResolver를 많이 등록시키는게 괜찮을지 잘 모르겠어서 구현하진 않았습니다 🫠🫠

별도의 객체가 필요한 경우 마다 ArgumentResolver에 등록하게 되면
비즈니스 로직이 예상치 못한 곳에 숨게되어버리기 때문에 지양해아한다고 생각해요!
ArgumentResolver 는 약속된 상황에서 제한적으로 사용해야한다고 생각합니다 :)

2023-01-19 04:42 UTC, pyun0825 commented on src/main/java/nextstep/auth/TokenGenDto.java
> +    private final Role role;
중간에 권한이 바뀌면 기존 토큰을 막거나 하는 추가적인 오버헤드가 발생할 거 같습니다! 변경 가능한 값은 최대한 토큰에 담지 않는게 좋을거 같네요 🙂

2023-01-19 05:52 UTC, pyun0825 commented on src/main/java/nextstep/auth/RoleInterceptor.java
> +    }
현재 admin관련 기능들은 인증, 인가 과정만 필요하고 나머지 api중 몇개는 아무 role이나 상관 없어서 인증 과정만 진행한 후 객체 반환이 필요한 상태입니다! 그래서 지금 상태에서 RoleInterceptor에서 멤버 객체를 불러와 확인하게 인증 과정만 추가하면 현재 기능 스펙에 대한 만족은 될거 같긴합니다.

그런데 다른 기능들이 추가된다고 가정하면 인증, 인가 과정과 로그인 객체 반환이 모두 필요한 경우가 무조건 생길 거 같아서 요한이 피드백해주신 내용으로 바꾸는게 더 좋은 설계인 거 같습니다!

그래서 그렇게 구현하려고 admin role이 필요하지 않은 모든 api들에 대한 interceptor를 추가하려 했는데 그러면 로그인이 필요하지 않은, 인증이 불필요한 api들이 애매해져서 고민입니다. Interceptor에서 인증을 진행하되 ArgumentResolver에 optional<Member> 같은 객체를 넘겨 인증이 실패한 경우 예외는 ArgumentResolver에서 터트릴지 아니면 이 신규 interceptor를 인증만 필요한 api path에 일일이 따로 매핑할지.. 어떤게 더 좋은 선택일지 궁금합니다!

2023-01-25 00:51 UTC, pyun0825 commented
연휴가 끝나버렸네요 요한 🥲

이번주도 잘 부탁드립니다!

- 이번에는 피드백 주신 내용 바탕으로 Interceptor에서 인증, 인가를 모두 처리하고 Resolver에선 메소드에서 필요한 객체로의 변환만을 수행하게 바꿔봤습니다.
- 그렇게 하려다 보니 interceptor에서 인증, 인가를 처리하기 위해 Member 객체를 쿼리하는데, 이후 Resolver로 정보를 넘길 때 Member 객체 자체를 넘길지 id와 같은 정보만 넘길지 고민하다 Resolver에서 쿼리를 다시 호출하지 않도록 객체 자체를 넘겼습니다.
- 그리고 LoginInterceptor가 특정 path의 특정 method에만 적용이 되도록 하고 싶었는데 interceptor 등록 시 따로 메소드를 지정할 수 있는 기능이 없었습니다.
- 그래서 블로그들을 참조해서 프록시 역할을 하는 PathMatchInterceptor를 추가해 Path와 Method까지 일치할 때 LoginInterceptor를 거치게 만들었습니다 🫠
- 지금은 PathMatchInterceptor를 거쳐야 하는 인터셉터가 LoginInterceptor 하나뿐이어서 이거를 스프링 빈으로 등록해서 싱글톤으로 사용해도 문제가 없었습니다. 그런데 추후 AdminInterceptor 등 다른 인터셉터들도 method match 해주는 기능이 필요해지게 되면 다수의 PathMatchInterceptor 객체가 필요할 것 같습니다. 그런 경우엔 스프링 빈으로 만들지 않고 직접 new 호출자로 객체를 생성해서 등록해주는 방법을 사용하는게 맞을까요?

2023-01-25 02:38 UTC, leeyohan93 approved these changes
안녕하세요 우기~
피드백을 잘 반영해주셨네요 👍 
질문 주신 부분에 대해서는 코멘트 남겨두었습니 확인 부탁드려요 :)
이번 단계도 고생 많으셨습니다 😄

2023-01-25 02:38 UTC, leeyohan93 commented on src/main/java/nextstep/auth/AdminRoleInterceptor.java
> +        return HandlerInterceptor.super.preHandle(request, response, handler);
> interceptor에서 인증, 인가를 처리하기 위해 Member 객체를 쿼리하는데, 이후 Resolver로 정보를 넘길 때 Member 객체 자체를 넘길지 id와 같은 정보만 넘길지 고민하다 Resolver에서 쿼리를 다시 호출하지 않도록 객체 자체를 넘겼습니다.

관련해서 Spring Security 에서는 로그인 정보를 스레드 로컬을 활용한 SecurityContextHolder를 통해 정보를 저장하고, 사용하는데요! 다른 방법도 한번 궁금하시면 살펴보셔도 좋을 것 같아요~ 이 방법이 꼭 더 좋은 방법은 아닙니다!

https://docs.spring.io/spring-security/site/docs/4.2.3.RELEASE/reference/htmlsingle/#securitycontextholder-securitycontext-and-authentication-objects

2023-01-25 02:38 UTC, leeyohan93 commented on src/main/java/nextstep/auth/PathMatchInterceptor.java
> +public class PathMatchInterceptor implements HandlerInterceptor {
> 그리고 LoginInterceptor가 특정 path의 특정 method에만 적용이 되도록 하고 싶었는데 interceptor 등록 시 따로 메소드를 지정할 수 있는 기능이 없었습니다.
그래서 블로그들을 참조해서 프록시 역할을 하는 PathMatchInterceptor를 추가해 Path와 Method까지 일치할 때 LoginInterceptor를 거치게 만들었습니다 🫠

HTTP Method 까지 매칭시킬 수 있도록 구현해주셨네요 💯 💯 
새로운 요구사항을 생각해보고 도전해보시는 모습이 좋습니다! 👍 
다른 방법으로는 로그인을 원하는 컨트롤러 메서드에 마킹 어노테이션을 설정해주는 방법도 있을 것 같아요!
(저희 팀에서는 주로 이 방식을 사용합니다.. ㅎㅎ)

> 지금은 PathMatchInterceptor를 거쳐야 하는 인터셉터가 LoginInterceptor 하나뿐이어서 이거를 스프링 빈으로 등록해서 싱글톤으로 사용해도 문제가 없었습니다. 그런데 추후 AdminInterceptor 등 다른 인터셉터들도 method match 해주는 기능이 필요해지게 되면 다수의 PathMatchInterceptor 객체가 필요할 것 같습니다. 그런 경우엔 스프링 빈으로 만들지 않고 직접 new 호출자로 객체를 생성해서 등록해주는 방법을 사용하는게 맞을까요?

네 꼭 스프링 빈으로 등록해서 사용할 필요는 없습니다. 생성자를 통해 유연성 있는 객체를 만들어서 사용하시면 좋을 것 같아요 :)

2023-01-25 02:38 UTC, leeyohan93 commented on src/main/java/nextstep/auth/AdminRoleInterceptor.java
> +        }
LoginInterceptor 와 동일한 기능을 하는 부분이 AdminRoleInterceptor 에도 존재하네요!
인터셉터 등록시 순서를 부여하여 LoginInterceptor 를 처리한 후에 AdminRoleInterceptor 해서 중복 코드를 제거하면, 각각 응집도를 높여볼 수도 있을 것 같아요!

만약 Jwt 인증 방식이 변경된다면 LoginInterceptor 와 AdminRoleInterceptor 모두를 수정하게 되는 상황을 고려해보시면 좋을 것 같습니다 :)

2023-01-25 02:38 UTC, merged