[herbi.sf8] 방탈출 인증관리 Step1,2
2023newkrew/spring-roomesacpe-auth-kakao pull request #54
Opened 2023-01-19 04:48 UTC by herbi1411

안녕하세요! 이번주 과제인 방탈출 인증관리 1,2단계 제출하겠습니다.
페어와의 일정 조정, ArgumentResolvers 개념 학습으로 인해 제출이 많이 늦어졌습니다.

1,2차 미션은 JWT를 통해 계정 인증을 통해 토큰을 발급하고, 토큰으로 사용자 인증을 하는 로직을 구현하는 것이었습니다! 또 토큰을 통해 인증된 사용자만 예약을 생성할 수 있고, 본인의 예약만 삭제할 수 있도록 처리했습니다.

기존에 주어진 뼈대코드가 많은데 뼈대코드의 수정을 최소화하고자 했지만 로직변경으로 인해 변경된 부분이 있습니다. 수정한 파일은 README에 명시했습니다.

저번 수업에 WebMvcTest를 배웠는데 이를 활용해보고자 AuthControllerTest를 추가해 봤습니다. E2E 테스트가 아니라 Mock을 통해 한 계층을 독립적으로 테스트할 수 있어서 좋은 것 같습니다.

3차미션은 Interceptor를 활용해 관리자 기능을 추가하는 것인데, 관련 개념 학습해서 활용하도록 하겠습니다!

2023-01-21 07:32 UTC, maythree requested changes
고생 많으셨습니다.
지금도 잘하시고 계시긴 하지만 사용하지 않는 코드에 대한 관리를 조금 더 신경써서 해주시면 코드 품질이 더욱 좋아지실 것 같습니다.👍

2023-01-21 07:32 UTC, maythree commented on src/main/java/nextstep/auth/AuthService.java
> +
MemberService가 따로 존재하는데 Member에 대한 검증을 여기서 하는 이유가 무엇일까요??

2023-01-21 07:32 UTC, maythree commented on src/main/java/nextstep/auth/JwtTokenProvider.java
> -    private long validityInMilliseconds = 3600000;
상수를 다시 정의해서 사용하신 이유가 무엇일까요?

2023-01-21 07:32 UTC, maythree commented on src/main/java/nextstep/member/MemberService.java
사용되지 않는 메소드인데 유지하신이유가 따로 있으실까요?? 이유가 있다면 주석으로 남겨놓은 이유를 적어놓으신다면 더욱 좋습니다.

2023-01-21 07:32 UTC, maythree commented on src/main/java/nextstep/reservation/Reservation.java
> +
생성자에 매개변수가 많다면 빌더 패턴을 고려해보셔도 좋으실 것 같습니다. 추가로 점층적 생성자 패턴과 빌더패턴의 차이에 대해서도 학습해보시면 좋으실 것 같습니다.

2023-01-21 07:32 UTC, maythree commented on src/main/java/nextstep/reservation/ReservationDao.java
>      public Reservation findById(Long id) {
여기서 예외 발생시 null로 처리하시는데, null로 처리하시는 것은 NPE 발생을 초래하기 때문에 지양하시는게 좋으실 것 같습니다.

2023-01-21 07:32 UTC, maythree commented on src/main/java/nextstep/reservation/ReservationService.java
>          Schedule schedule = scheduleDao.findById(reservationRequest.getScheduleId());
Optional에 대해서 학습해보시고 활용하시면 좋으실 것 같습니다.

2023-01-21 07:32 UTC, maythree commented on src/main/java/nextstep/reservation/ReservationService.java
>          if (!reservation.isEmpty()) {
reservation이 null로 반환되면 어떻게 되나요?

2023-01-23 06:46 UTC, herbi1411 commented on src/main/java/nextstep/auth/AuthService.java
> +
말씀해주신대로 AuthService에 멤버를 검증하는 로직이 들어가는 것은 어색한 것 같습니다. AuthController가 MemberService를 가지도록 해서 멤버를 검증하고 AuthService로 들어가도록 수정했습니다! 비밀번호 검증 로직은 Member 도메인의 메서드를 활용하기 때문에 AuthService에서 인자로 받은 Member의 메서드로 검증했습니다.

2023-01-23 06:46 UTC, herbi1411 commented on src/main/java/nextstep/auth/JwtTokenProvider.java
> -    private long validityInMilliseconds = 3600000;
상수 관리하는 파일로 빼는 과정에서 기존 파일 상수에 값을 단순히 대입을 하는 구조로 바꿨었네요. 필요없이 2번 선언된 것 같습니다. 선언 없이 바로 값을 사용하도록 수정했습니다!

2023-01-23 06:46 UTC, herbi1411 commented on src/main/java/nextstep/member/MemberService.java
id로 Member를 조회하는 로직이 사용되지 않는다는 것을 놓쳤습니다. dao, service에서 해당 부분을 삭제했습니다!

2023-01-23 06:46 UTC, herbi1411 commented on src/main/java/nextstep/reservation/Reservation.java
> +
뼈대코드가 많아서 프로젝트에 빌더패턴을 사용할까 말까 고민했는데 롬복 사용해서 적용해봤습니다!! 기존 코드에서도 말씀해주신 점층적 생성자 패턴을 사용했었으면 도메인 코드가 더 깔끔했을 것 같습니다. 빌더 패턴과 점층적 생성자 패턴과의 차이도 알아봤는데, 빌터 패턴에서 builder 클래스의 생성자로 필수 인자 값을 넣고, 나머지 인자는 메서드로 넣는 다는 것을 알게됐습니다! 저는 도메인 계층에서 Notnull 어노테이션을 사용해 필수 인자를 받도록 했습니다! 또 Response를 담당하는 DTO에는 생성자를 private으로 만들어서 팩토리 메서드로만 객체를 생성할 수 있도록 했습니다.

2023-01-23 06:47 UTC, herbi1411 commented on src/main/java/nextstep/reservation/ReservationDao.java
>      public Reservation findById(Long id) {
기존에는 DAO에서 null을 반환하면 service에서 null 검사를 하는 구조였네요. 말씀해주신대로 null을 바로 반환하는 것은 좋은 방법이 아닌 것 같습니다. 해당 부분을 optional로 감싸서 반환하고 service에서 값이 비어있으면 예외처리하는 방법으로 NPE를 방지했습니다!

2023-01-23 06:47 UTC, herbi1411 commented on src/main/java/nextstep/reservation/ReservationService.java
>          Schedule schedule = scheduleDao.findById(reservationRequest.getScheduleId());
id로 스케줄을 조회할 때 optional을 통해 존재하지 않으면 예외를 던지도록 수정했습니다! Schedule 외에도 DAO에서 id로 조회하는 부분은 모두 optional을 사용하도록 했습니다!

2023-01-23 06:47 UTC, herbi1411 commented on src/main/java/nextstep/reservation/ReservationService.java
>          if (!reservation.isEmpty()) {
reservation이 null이면 isEmpty()를 호출할 때 NPE가 발생합니다. 따라서 if문 앞에 reservation이 null인지 먼저 검사하도록 했습니다! 그런데 해당 코드는 예약을 생성할 때 ReservationRequest로 들어온 schedule이 이미 다른 예약에 있는 지를 검사해서 없을 때 예약을 생성합니다. 즉, ReservationDao의 findByScheduleId를 실행했을 때 빈 리스트로 반환되면 예약을 생성하는데요. 테스트 코드에서 예약 생성이 작동하는 것을 보니 jdbctemplate의 query 메서드에서 값을 찾을 수 없을 때 빈 리스트를 반환하는 것 같은데  null이 반환되는 경우가 따로 있는 것일까요?? 인터넷 검색을 했을 때는 List<T>를 반환한다고 돼있어서 null을 반환하는 경우가 따로 있는 지를 찾지 못했습니다.

2023-01-23 06:59 UTC, herbi1411 commented
바쁘셨을텐데 리뷰 남겨주셔서 정말 감사드립니다!!🙂 말씀해주신 부분 수정완료 해서 일단 리뷰 요청 다시 드리겠습니다! 나중에 편하신 시간에 봐주세요. 남은 명절연휴도 잘보내세요!!👏

2023-01-23 07:25 UTC, maythree commented on src/main/java/nextstep/reservation/ReservationService.java
>          if (!reservation.isEmpty()) {
@herbi1411 
기존 수정하시기전에 findByScheduleId가 예외 발생시 null이 반환되게 처리가 되어 있어서 코멘틀를 남겼었습니다. 지금은 수정하여 문제 없을 것 같습니다.👍

2023-01-23 07:30 UTC, maythree approved these changes
고생 많으셨습니다👍👍

2023-01-23 07:30 UTC, merged

2023-01-23 12:00 UTC, herbi1411 commented on src/main/java/nextstep/reservation/ReservationService.java
>          if (!reservation.isEmpty()) {
앗 제가 이미 수정해버리고 나서 찾고있었군요...😅 감사합니다!!