[minion.mo] 방탈출 인증 관리 step3
2023newkrew/spring-roomesacpe-auth-kakao pull request #58
Opened 2023-01-19 07:18 UTC by gusah009

안녕하세요 조엘! 이번에도 잘부탁드립니다!!

33f8555c10d5f8628582b2e3a9ee1b685096aac4 이 커밋부터 보시면 될 것 같아요!

리뷰해주신 내용들과 step3 요구사항을 반영해봤습니다! 점점 레거시 코드가 커질수록 관리가 어려워지네요..!

2023-01-20 04:14 UTC, haewon13 requested changes
고생 많으셨습니다 미니언~
기존에 ArgumentResolver에서 하던 토큰 인증 검증을 Interceptor에서 하게끔 처리해서, Resolver에서는 인증 검증된 토큰에서 필요한 파라미터만 처리될 수 있게 한거 아주 좋습니다!
Resolver와 Interceptor의 각 역할과 인증/인가에 대해서 잘 이해해주신 것 같아요~

전반적으로 잘 구현해주셨지만 욕심에.. 조금만 더 개선시키면 좋을 부분들이 보여서 코멘트 달았습니다 :)

2023-01-20 04:14 UTC, haewon13 commented on src/main/java/nextstep/reservation/ReservationService.java
> +    public void cancle(long authId, long reservationId) {
앗 오탈자가 있네요ㅎㅎ

2023-01-20 04:14 UTC, haewon13 commented on src/main/java/nextstep/auth/role/Role.java
> +}
enum 관리 👍

2023-01-20 04:14 UTC, haewon13 commented on src/main/java/nextstep/exception/ExceptionAdvice.java
> +                .body(e.getMessage());
앗! 기존에 인증, 인가 관련 에러를 분리해두신건 좋았습니다~ (authentication, authorization)
인증, 인가 관련된 에러들은 실무에서도 많이들 분리해서 관리하고 있고요! not found 같은류의 에러들도 businessException으로 같이 묶이기에는 역할이 다른것 같아요!
내 예약이 아닌 다른 예약을 수정하려고 하거나 신청하려고 하는 시간대에 이미 다른 예약이 있다던가 하는 케이스들만 businessException으로 처리되면 좋을 것 같네요~ 
어떤식으로 그룹핑하면 좋을지 한번더 고민해봐주세요!

+) 그 외 internal server 에러에 대해서도 고민 부탁드릴게요!

2023-01-20 04:14 UTC, haewon13 commented on src/main/java/nextstep/config/WebMvcConfiguration.java
> +        registry.addInterceptor(new UserInterceptor(jwtTokenProvider)).addPathPatterns("/admin/**", "/reservations/**");
Controller단들을 살펴보니 크게
- 누구나 요청 가능한 /login
- admin만 사용가능한 /admin
- 그외 로그인한 유저만 요청가능한 API들
로 분리할 수 있을것 같은데요! /members 나 예약조회같은 API들은 인증에서 빠지게 된것 같아요 

UserInterceptor에서 로그인 단계 이후부터는 모두 체크해야 하는 로그인여부 인증을 확인하는데 path를 하나하나 추가하다보면 빠트릴 수도 있을것 같고요! 
가장 기본적인 인증을 체크하는 곳에서는 전체 path를 넣되, 로그인하지 않은 유저도 접근 가능한 path들을 exclude 처리하는 방향은 어떠실까요? 제안드려봅니다~

2023-01-25 01:10 UTC, gusah009 commented on src/main/java/nextstep/reservation/ReservationService.java
> +    public void cancle(long authId, long reservationId) {
헉 그러네요..!

2023-01-25 01:25 UTC, gusah009 commented on src/main/java/nextstep/exception/ExceptionAdvice.java
> +                .body(e.getMessage());
넵! 레이어드 계층에 따라서 각 레이어에 해당하는 `Exception`으로 분리해봐야겠네요!

![image](https://user-images.githubusercontent.com/26597702/214459448-254afa53-c4a8-4936-bc18-4f02083d5378.png)

2023-01-25 07:04 UTC, gusah009 commented on src/main/java/nextstep/config/WebMvcConfiguration.java
> +        registry.addInterceptor(new UserInterceptor(jwtTokenProvider)).addPathPatterns("/admin/**", "/reservations/**");
`exclude`로 처리해봤습니다!! 좋은 리뷰 감사합니다 🙇‍♂️

2023-01-26 02:05 UTC, haewon13 approved these changes
피드백 잘 반영해주셨네요 👍 고생하셨습니다!

2023-01-26 02:05 UTC, merged