[kloong.96] 방탈출 인증 미션 3단계 - 관리자 기능 추가
2023newkrew/spring-roomesacpe-auth-kakao pull request #69
Opened 2023-01-24 16:47 UTC by Kloong1

안녕하세요 네소이!
설 연휴는 잘 보내셨나요 ㅎㅎ
연휴가 끝나자마자 일거리를 드리는 것 같아서 조금 민망하지만, 리뷰 요청 드립니다 ㅎㅎ...

생각보다 연휴때 과제를 할 시간이 없어서 급하게 마무리 하느라 퀄리티가 많이 떨어지는 느낌이 있네요 ㅜㅜ
이전 단계에서 리팩토링 못했던 부분을 연휴 기간동안 최대한 개선해서 제출을 하려고 했는데, 리팩토링은 커녕 3단계 기능 구현도 겨우 해서 제출합니다.... ㅜㅜ
뭔가 가면 갈수록 완성도가 떨어지는 코드를 드리는 것 같은데, 연휴때 그래도 잘 쉬었으니 다음 과제부터 또 힘을 내서 최대한 좋은 코드 작성하려고 노력해보겠습니다.

## 이번 단계에서 추가/변경 된 점

### 관리자 추가
일반 사용자가 방탈출 테마와 스케줄 생성/삭제 요청을 보내면 문제가 생기기 때문에, "관리자"를 추가해서 해당 요청은 관리자만 가능하게 끔 기능을 구현하는 게 이번 단계의 목표였습니다.

그래서 `admin` 패키지를 추가하고, 도메인, dao, dto 등을 추가했습니다. 또 DB에 ADMIN 테이블도 추가했습니다.
그리고 `AuthController`에 관리자 로그인 요청 시 usernamer과 password를 검증해서 토큰을 반환하는 로직을 구현했습니다.

### "/admin/**" 요청에 대한 인증 인터셉터 추가
관리자만 가능한 요청에 대해서 인증을 하는 `AdminAuthInterceptor`를 추가했습니다.
헤더에서 토큰을 읽어서 username을 추출한 뒤 해당 username이 Admin DB에 존재하는 지 확인하는 식으로 인증을 합니다.

### 테마와 스케줄 생성/삭제 요청 URI 앞에 `/admin` 추가
`AdminAuthInterceptor`가 해당 요청 앞단에서 인증 로직을 수행할 수 있도록 URI를 변경했습니다.

### 추가
과제 요구사항에서 관리자 등록은 스프링 부트에서 제공하는 기능을 이용하라고 해서 `resources/data.sql`에 insert 구문을 추가해뒀습니다.

또 지난 단계 마지막 리뷰에서 언급하신 
<img width="804" alt="스크린샷 2023-01-25 오전 1 42 20" src="https://user-images.githubusercontent.com/16686954/214354143-2dd0ef8c-1f53-4e4c-b701-f4ec8292e7bd.png">

이 내용도 고민을 해봤는데, 리뷰해주셨을 당시에는 정확히 무슨 의미인지 감이 안왔었습니다.
그런데 이 관리자 인증의 경우가 "대부분의 API 요청에 인증 프로세스가 적용되는 경우" 구나 라는 걸 이번 단계를 진행하면서 알게 되었네요.
관리자 인증 인터셉터 추가하면서, 말씀하신 `members/me` 요청에 대한 인터셉터도 추가하려고 했는데, 저기서는 아무래도 `Member` 객체를 바디에 넣어서 응답을 해줘야 하다 보니 따로 수정 안하고 그대로 두었습니다 ㅎㅎ...

잘 부탁드립니다!

2023-01-25 05:15 UTC, NESOY requested changes
중요한건 배우는 과정이니까 퀄리티가 많이 떨어졌다고.. 자책하지 않으셔도 됩니다 ㅎㅎ 
- 인증과 인가에 대한 개념도 약간의 차이가 있기 때문에 찾아보면 좋을거 같습니다. 
  - 더 나아가면 - RBAC(Role-Based Access Control)
- 스프링팀은 어떻게 구현했나 궁금하시면 Spring Security 관련해서 찾아보면 더 좋을거 같습니다.
  - https://mangkyu.tistory.com/76

몇가지 댓글 남겨드렸고 설연휴동안 고생 많으셨습니다 🙇‍♂️

2023-01-25 05:15 UTC, NESOY commented on src/main/java/nextstep/support/AdminAuthInterceptor.java
> +            throw new NotExistEntityException(ErrorCode.USER_NOT_FOUND);
`User Not Found` 보다는 `401 Unauthorized` 에러가 더 좋지 않을까요? 🤔
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2023-01-25 05:15 UTC, NESOY commented on src/main/java/nextstep/admin/Admin.java
> +public class Admin {
나중에 어드민보다 더 다양한 역할이 오는 경우에도 매번 새로운 클래스를 만들어야 할까요? 🤔
아니면 기존 멤버 테이블과 어떻게 통합하고 관리할 수 있을까요?

2023-01-25 05:15 UTC, NESOY commented on src/main/java/nextstep/config/WebMvcConfiguration.java
> +                .addPathPatterns("/admin/**");
요구 사항은 만족했지만.. 더 생각해보면..?
- 예를 들어 10,000명이 개발자과 같이 협업을 하면.. `/admin` 규칙을 모르고 놓칠 수도 있는 휴먼 에러가 발생할 확률이 높을거 같아요.
- 그래서 기본적으로 API에 인증/인가 절차를 요구하고, 예외를 두는 방식으로 진행하는 케이스가 많습니다. 
- `기본적으로 API에 인증/인가 절차를 요구하고, 예외를 두는 방식으로 진행하는 케이스`으로 바꾸려면 어떻게 해야할까요?

2023-01-25 05:15 UTC, NESOY commented on src/main/java/nextstep/schedule/ScheduleController.java
> +    @PostMapping("/admin/schedules")
현실 세계에서 API 주소를 변경하는 건.. 클라이언트, 웹등 많은 사람들이 필요해서 매우 큰 비용이 듭니다ㅠ
API 변경 대신 인증 절차를 쉽게 할 수 있는 방식은 없을까요?
ex) interceptor에서 메소드에 허용된 annotation이 존재하면 인증 절차를 진행한다든지?

2023-01-25 05:15 UTC, NESOY commented on src/main/java/nextstep/support/AdminAuthInterceptor.java
> +        String username = jwtTokenProvider.getPrincipal(token);
NIT:
LoginMemberArgumentResolver에도 동일한 코드가 있는데 중복처리를 어떻게 하면 좋을까요?

2023-01-25 14:33 UTC, Kloong1 commented
안녕하세요 네소이!
리뷰해주신 부분들 적용해보았습니다.

### Admin 도메인 삭제하고 Role 도입
리뷰해주신 대로 역할이 추가될 때마다 DB 테이블과 클래스를 추가할 수는 없기 때문에, Role 이라는 enum과 테이블을 추가했습니다.
Role 테이블은 Member가 가질 수 있는 역할을 id, name 두 개의 컬럼 형태로 저장하는 테이블입니다.
Role enum은 Role 테이블의 name과 동일한 이름의 상수 객체를 가지게 했습니다.

그리고 Member의 필드로 Role을 추가했습니다.
또 Member 테이블에는 Role 의 id 컬럼을 참조하는 외래키, role_id를 추가했습니다.

이런 식으로 Role 을 통해 Member의 역할을 나타낼 수 있게 했습니다.

### `@Auth` 어노테이션 추가, `AdminAuthInterceptor` 변경
`AdminAuthInterceptor`가 요구사항에 인증이 필요 없다고 명시된 일부 URI 를 제외하고는 전부 인증을 시도하도록 인터셉터 등록시에 pathPattern을 지정해주었습니다.
단 HandlerMethod에 `@Auth(role = Role.ADMIN)` 어노테이션이 붙어있는 경우에만 인증 로직을 실행하고, 나머지 경우에는 true를 반환하도록 로직을 구현해두었습니다.

또 말씀하신대로 기존 API 중 인증이 필요한 API에만 `/admin`을 붙이는 게 좀 이상하게 느껴졌는데(과제 요구사항이긴 해서 그대로 하긴 했지만), 언급하신 변경에 대한 비용 문제나 협업에서 발생할 수 있는 문제에 대해서는 전혀 생각해보지 못했었습니다.

이 문제를 해결하기 위해서 `@Auth` 어노테이션을 도입함으로써 추후에 특정 API가 인증이 필요하게 스펙이 바뀌더라도 어노테이션 하나만 붙이는 것을 통해 인증 절차를 추가할 수 있도록 했습니다
(`/admin` URI 붙이는 건 과제 요구사항이라서 따로 없애지는 않았습니다)

### `AdminAuthInterceptor`와 `LoginMemberArgumentResolver` 중복 제거
토큰을 추출할 때 발생하는 예외 처리 코드를 `AuthorizationTokenExtractor` 내부로 집어 넣어서 중복 코드를 최소화했습니다.
뭔가 더 깔끔한 방법이 있을까 싶긴 한데 잘 모르겠네요 흠...

바쁘실텐데 짬내서 리뷰 해주셔서 감사합니다!

2023-01-30 01:03 UTC, NESOY approved these changes
@Kloong1 고생많으셨습니다. :)
+ Review Request 버튼 눌러주시면 감사하겠습니다. 알림이 따로 안오네요 ㅠ

2023-01-30 01:03 UTC, merged