[woogie.pyun] 인증관리 - Step1 & 2
2023newkrew/spring-roomesacpe-auth-kakao pull request #7
Opened 2023-01-17 00:54 UTC by pyun0825

안녕하세요 요한!

이번에는 인증과 ArgumentResolver 관련 학습을 진행해봤습니다!

저번 미션과 거의 유사한 기능을 하는 스켈레톤 코드가 미리 작성되어 주어졌는데 여기서 인증 처리하는 부분만 저희가 추가적으로 구현하고 수정했습니다.

스켈레톤 코드에 개선할 수 있는 부분이 상당히 많아보이긴 하는데 그 부분에 대한 리펙토링은 사실상 저번 미션 다시 만드는 것과 똑같을 거 같아서 일단은 불편해도 최대한 스켈레톤 코드를 안 바꾸고 유저 인증에 대한 부분만 건드려 봤습니다 🫠

궁금했던 점들 몇가지 코멘트로 남기겠습니다!

2023-01-17 00:55 UTC, pyun0825 commented
**JWT에 담을 값**
- JWT에 담는 유저를 식별할 정보로 `memberId`와 `username`중 어떤걸 담게 할지 고민했습니다. 제공된 스켈레톤 코드를 보니 `username`으로 `Member` 객체를 쿼리하는 메소드의 구현 상 `username`도 unique한 성질이 있다고 가정하고 작성된 것 같아 처음에는 `username`을 담게 했으나 일단은 `memberId`를 담게 다시 바꿨습니다.
- DB의 ID 값도 다른 API 등에서 결국 노출되는 값이니 JWT에 담아도 괜찮은 내용일까요?

**비밀번호 검증 로직**
- 유저의 비밀번호 검증하는 로직을 `MemberService`에 구현을 해야할지 별도의 `AuthService`를 만들어 구현해야 할지 고민했습니다.
- `Member`의 값들을 비교하는 작업이니 `MemberService`에 구현을 해야하나 싶었지만 로그인 과정에서만 쓰이는 로직이라 `AuthService`를 따로 추가해서 거기에 구현했습니다.

**ArgumentResolver에서 service호출**
- `HandlerMethodArgumentResolver`를 구현한 `AuthenticationPrincipalArgumentResolver`에서 resolve해서 반환해줄 객체로 어떤걸 하는게 맞을지 고민입니다.
- 헤더에서부터 JWT를 가져와 검증하는 과정 이후, `MemberService`나 `Dao`를 주입받아 사용해 실제 멤버 객체를 반환해야할지 지금처럼 토큰에 담긴 유저 정보(id)만 추출해 반환하는게 맞을지 모르겠습니다.
- `Service`나 `Dao` 객체가 이런 `Resolver`에서 쓰여도 되는지가 의문입니다.

2023-01-17 05:31 UTC, leeyohan93 requested changes
우기 안녕하세요~
빠르게 잘 구현해주시고 PR 요청 주셨네요! 👍 👍 
질문에 대한 코멘트 남겨 두었으니 확인 부탁드려요!

2023-01-17 05:31 UTC, leeyohan93 commented on src/main/java/nextstep/auth/AuthController.java
> +        return ResponseEntity.ok(new TokenResponse(accessToken));
> 인증 로직은 Controller에서 구현하기 보다는 재사용이 용이하도록 분리하여 구현하다.
가능하면 Controller와 인증 로직을 분리한다.

위 요구사항을 만족하고 있는 지 고민해보시면 좋을 것 같아요!
만약 tokenProvider가 변경되면 Controller 의 로직을 변경해야되지 않을까요?

2023-01-17 05:31 UTC, leeyohan93 commented on src/main/java/nextstep/auth/AuthService.java
> +        return member.getId();
> DB의 ID 값도 다른 API 등에서 결국 노출되는 값이니 JWT에 담아도 괜찮은 내용일까요?

네! 유저의 유니크한 값으로 식별 가능한 값이라면 DB의 id 값을 담아도 괜찮다고 생각합니다.
jwt 토큰으로 암호화되기도하고, 보통 데이터베이스의 id 값은 유저의 개인정보와 관계 없는 
auto increment 값을 사용하기 때문입니다 :)

2023-01-17 05:31 UTC, leeyohan93 commented on src/main/java/nextstep/auth/AuthService.java
> +    public Long validateAndGetMemberId(TokenRequest tokenRequest) {
메서드 네이밍처럼 하나의 메서드가 두가지 일을 하고 있네요! 
하나의 메서드가 하나의 일을 하도록 변경해보면 어떨까요?

2023-01-17 05:31 UTC, leeyohan93 commented on src/main/java/nextstep/auth/AuthenticationPrincipal.java
> +public @interface AuthenticationPrincipal {
커스텀 어노테이션 사용 👍 👍

2023-01-17 05:31 UTC, leeyohan93 commented on src/main/java/nextstep/auth/AuthenticationPrincipalArgumentResolver.java
> +        return Long.parseLong(jwtTokenProvider.getPrincipal(token));
> HandlerMethodArgumentResolver를 구현한 AuthenticationPrincipalArgumentResolver에서 resolve해서 반환해줄 객체로 어떤걸 하는게 맞을지 고민입니다.

저는 개인적으로는 로그인된 회원을 반환하는 객체를 만들어 사용하는 것을 지향합니다.
어떤 객체로 해야한다는 정답은 없으니 상황에 맞게 편리하게 사용할 수 있는 것으로 설정해주시면 좋을 것 같아요 :)

2023-01-17 05:31 UTC, leeyohan93 commented on src/main/java/nextstep/auth/AuthenticationPrincipalArgumentResolver.java
> +    private final JwtTokenProvider jwtTokenProvider;
> Service나 Dao 객체가 이런 Resolver에서 쓰여도 되는지가 의문입니다.

스프링을 사용하다보면 편의성을 위해 `레이어드 아키텍처` 에 관계 없이 서비스 또는 영속성 계층의 객체를 사용하게 됩니다.
이러한 부분은 스프링에서 지원해주는 편리함을 사용하기 위해 트레이드 오프의 영역이라고 생각해요!
기존의 Service, Dao 객체를 사용하거나 별도의 서비스를 구현하는 것도 하나의 방법이라고 생각합니다 :)

2023-01-17 05:31 UTC, leeyohan93 commented on src/main/java/nextstep/auth/AuthService.java
> +        if (member.checkWrongPassword(tokenRequest.getPassword())) {
> 유저의 비밀번호 검증하는 로직을 MemberService에 구현을 해야할지 별도의 AuthService를 만들어 구현해야 할지 고민했습니다.

저는 별도의 인증 서비스를 만드는 것도 좋은 방법이라고 생각해요! 😄

2023-01-17 05:31 UTC, leeyohan93 commented on src/main/java/nextstep/auth/AuthenticationPrincipal.java
> +    boolean required() default true;
required 는 어디에 사용될 의도였을까요?

2023-01-17 05:32 UTC, leeyohan93 commented on src/main/java/nextstep/reservation/ReservationService.java
> +        }
유저 정보를 한번 조회해서 검증되었는데, 다시 조회하니 불필요한 코드가 생기고 있네요!
개선해볼 포인트인 것 같습니다 :)

2023-01-17 06:27 UTC, pyun0825 commented on src/main/java/nextstep/auth/AuthenticationPrincipal.java
> +    boolean required() default true;
학습 테스트를 참고하면서 `required=true/false`로 로그인 여부를 체크할 수 있지 않을까 싶어서 유지시켰는데 결과적으로 전혀 필요 없었던 것 같습니다..! 😅

2023-01-17 09:40 UTC, pyun0825 commented
매번 꼼꼼한 리뷰 감사합니다 요한 🙏

피드백 반영해서 리팩토링 진행해봤습니다!

- `tokenProvider`에 컨트롤러가 의존하고 있는 걸 최대한 없애려 `tokenProvider`를 호출하고 토큰을 발급 받는걸 `AuthService`에서 하도록 레이어를 한단계 낮췄습니다.
- 추가적으로 `AuthService`에 기존 메소드들이 하나의 일만 하도록 분리해 봤습니다!
- `ArgumentResolver`에서 `Member`객체를 반환하는 게 코드 작성하기에도 수월할 거 같아서 `MemberService`를 사용해서 `Member`객체를 반환하게 변경했습니다. 레이어드 아키텍쳐에 대한 공부를 추가적으로 해야될 거 같습니다 🙃 특정 레이어의 책임이 어떤거지라는 고민을 계속 하게 되네요 ㅎㅎ..
- `ArgumentResolver`에서 `Member` 객체를 반환하게 변경하니 로그인한 멤버의 `id` 말고 다른 정보를 얻기 위해 서비스에서 `Member` 객체를 다시 찾아 올 필요 가 없어져 불필요한 null check 같은 과정을 쉽게 없앨 수 있었던 거 같습니다!

2023-01-18 02:09 UTC, leeyohan93 approved these changes
꼼꼼하게 피드백 잘 반영해주셨네요! 💯 
참고하면 좋을 코멘트 하나 남겨두었으니 확인 부탁드릴게요 :)
감사합니다 🙏

2023-01-18 02:09 UTC, leeyohan93 commented on src/main/java/nextstep/auth/AuthenticationPrincipalArgumentResolver.java
> +        return loggedInMember;
만약 회원 관련된 서비스가 발전되어 현재의 Member 도메인 모델이 확장된다면 어떻게 될까요?
그 때는 Member 도메인 모델을 `로그인된 회원` 개념에 사용하기에 과할 수 도 있다고 생각합니다 :)
보통 로그인된 회원의 인자는 간단한 유저의 기본 정보 (id, name) 등을 활용하기 때문인데요!
이럴 때는 별도의 모델을 분리하는 것을 고민해야 할 때라고 생각합니다 :) 
참고해주세요! 😄

2023-01-18 02:09 UTC, merged