[asher.an] 인증 Step1, 2
2023newkrew/spring-roomesacpe-auth-kakao pull request #70
Opened 2023-01-24 18:57 UTC by mkom76

인증관리를 추가하는 미션이었습니다.
대부분의 구현은 auth패키지에서 진행하였습니다.

<auth>
기본적으로 토큰을 만들어주고 토큰에 대한 정보를 얻을 수 있는 Provider, Extractor가 제공됩니다(이 두 클래스는 스켈레톤코드에 포함되어 있었습니다).
사용자의 아이디와 비밀번호를 받아서 멤버 테이블에 존재하는지 확인 후 비밀번호가 맞으면 토큰을 발급하는 api를 제공합니다.
추가적으로 token의 유효성을 검증하는 Resolver가 있습니다. MVC configuration을 활용하여 컨트롤러에서 유효성을 검증할 수 있도록 구현했습니다.

<특이사항>
스켈레톤 코드에서 schedule 도메인이 추가되었는데, Reservation에서 관리하던 날짜/시간, 테마를 이 도메인에서 관리하네요. 인증 미션 자체에서는 크게 신경쓰지 않아도 되는 부분인 것 같습니다.

2023-01-25 05:48 UTC, scolleck requested changes
고생하셨습니다 몇가지 리뷰사항 남겨드리오니 확인 부탁드립니다 :)

2023-01-25 05:48 UTC, scolleck commented on build.gradle
> +
미사용 라이브러리 디펜던시는 제거해주세요 :)

2023-01-25 05:48 UTC, scolleck commented on src/main/java/nextstep/auth/config/AuthenticationPrincipalArgumentResolver.java
> +    JwtTokenProvider jwtTokenProvider;
접근제한자를 기재하는것이 좋지 않을까요?

2023-01-25 05:48 UTC, scolleck commented on src/main/java/nextstep/member/repository/MemberDao.java
> +            //e.printStackTrace();
로깅용 주석은 삭제하면 좋을 것 같습니다 :)

cf. log4j, slf4j 등 로깅 관련 프레임워크

2023-01-25 05:48 UTC, scolleck commented on src/main/java/nextstep/auth/config/AuthenticationPrincipal.java
> +public @interface AuthenticationPrincipal {
커스텀 어노테이션 설계와, 컨트롤러 메서드에서 특정 조건에 맞는 파라미터가 있을 때 원하는 값을 바인딩해주는 인터페이스를 활용하여 jwt 토큰 베이스 로그인 처리를 진행하셨군요, 좋은 경험이 될 것 입니다 :)

현재 구현에서는 컨트롤러 레벨에서 파라미터에 어노테이션을 적용하는 방식으로 이해됩니다.

실제로는 필터 또는 인터셉터를 활용하여 토큰에서 유저 auth 정보를 취득하는 식으로 모든 요청에 대해 적용하는 식으로 많이 활용됩니다:)

참고하여 시간나실때 필터와 인터셉터, 그리고 인증 관련된 부분을 숙지해두시면 좋을 것 같습니다

2023-01-25 05:48 UTC, scolleck commented on src/main/java/nextstep/auth/config/AuthorizationExtractor.java
> +    public static final String AUTHORIZATION = "Authorization";
해당 상수는 HttpHeaders.AUTHORIZATION 로 대체 가능해 보입니다. HttpHeaders 내에는 여러 상수가 정의되어있으니 참고해주세요 ~

2023-01-25 05:48 UTC, scolleck commented on src/main/java/nextstep/auth/controller/AuthController.java
> +@RestController
@RestController 와 @Controller의 차이를 숙지하고 계시면 좋을 것 같습니다 :)

2023-01-25 05:48 UTC, scolleck commented on src/main/java/nextstep/auth/controller/AuthController.java
> +        return ResponseEntity.ok().body(tokenResponse);
ResponseEntity.ok(tokenResponse) 와 같은 코드입니다.
인텔리제이의 네이게이터를 통해 따라 들어가서 확인해보시면 좋을 것 같아요 :)

2023-01-25 05:48 UTC, scolleck commented on src/main/java/nextstep/member/repository/MemberDao.java
> +            return null;
null을 직접 리턴하는 경우는 의도치않은 NPE를 유발 할 수 있으므로 유의해야 할 것 같습니다.

2023-01-25 05:48 UTC, scolleck commented on src/main/java/nextstep/auth/service/AuthService.java
> +        return actualMember.getPassword().equals(password);
String 관련 equals는 항상 null.equals 를 염두하여
StringUtils 사용하거나, 상수.equals 또는 Objects.equals 등을 활용하는것이 좋을 것 같습니다 :)

2023-01-25 08:28 UTC, mkom76 commented on build.gradle
> +
주석처리해둔거 자꾸 놓치네요ㅠㅠㅠ 의식해서 삭제하도록 하겠습니다!!

2023-01-25 08:41 UTC, mkom76 commented on src/main/java/nextstep/auth/config/AuthenticationPrincipalArgumentResolver.java
> +    JwtTokenProvider jwtTokenProvider;
추가하였습니다! 이상한 실수를 했네요..ㅠㅠ

2023-01-25 09:07 UTC, mkom76 commented on src/main/java/nextstep/member/repository/MemberDao.java
> +            //e.printStackTrace();
삭제했습니다! 로깅 프레임워크는 처음 봤는데, 기회가 생기면 활용해보겠습니다ㅎㅎ 
log4j는 검색하자마자 취약점부터 나오네요..ㅋㅋㅋ 취약점은 항상 가슴에 새겨두어야겠다는 것도 또한번 느낍니다!

2023-01-25 09:10 UTC, mkom76 commented on src/main/java/nextstep/auth/config/AuthenticationPrincipal.java
> +public @interface AuthenticationPrincipal {
3단계 요구사항이 인터셉터여서, 다음 미션에서 구현해보겠습니다!ㅎㅎ
현재 구현방식은 말씀하신대로 컨트롤러 파라미터에 어노테이션을 적용하여 토큰 유효성을 검사하는 방식입니다ㅎㅎ

2023-01-25 09:18 UTC, mkom76 commented on src/main/java/nextstep/auth/config/AuthorizationExtractor.java
> +    public static final String AUTHORIZATION = "Authorization";
와우 그렇네요! 모든 헤더에 대해 상수로 정의되어있군요!! 넘 편하네요ㅎㅎ 감사합니다!!

2023-01-25 09:38 UTC, mkom76 commented on src/main/java/nextstep/auth/controller/AuthController.java
> +@RestController
@Controller 가 기존 방식이었네요. view를 반환하기 위해 만들어진.. 여기에 객체를 담기 위해 @Responsebody를 사용했고, 이 두개를 합친 게 @RestController로 이해가 됩니다. JSON형태로 알아서 만들어주는게 정말 편하네요,, 어노테이션들은 정말 많이 알아둬야겠습니다ㅎㅎ 둘의 차이에 대해 생각을 안해봤는데, 이번기회에 알게 되었네요. 감사합니다!

2023-01-25 09:47 UTC, mkom76 commented on src/main/java/nextstep/auth/controller/AuthController.java
> +        return ResponseEntity.ok().body(tokenResponse);
헉.. 그렇네요. ok 메소드는 바로 넣어도 되는군요! 다른 메소드들(created, accepted 등)은 왜 이렇게 안만든건지는 잘 모르겠네요.. 그냥 개발자 마음인걸까요?ㅎㅎ.. 구글링해봐도 잘 안나오는데,, 혹시 심오한 뜻이 있을까요??

2023-01-25 09:55 UTC, mkom76 commented on src/main/java/nextstep/member/repository/MemberDao.java
> +            return null;
이전 미션 로직처럼 Optional로 해결했습니다!

2023-01-25 10:02 UTC, mkom76 commented on src/main/java/nextstep/auth/service/AuthService.java
> +        return actualMember.getPassword().equals(password);
위에 널체킹을 했다고 생각했는데 패스워드가 null일 수 있음을 간과했네요.. 수정하였습니다. 감사합니다!!

2023-01-26 02:33 UTC, scolleck commented on src/main/java/nextstep/auth/controller/AuthController.java
> +        return ResponseEntity.ok().body(tokenResponse);
다른 메소드들의 경우 body를 사용하지 않는 형태도 병행하기 때문에 기본형태에 body를 심는 형태로 구성되지 않았을것입니다.

보통 ok 응답에서는 그에 따른 결과인 body가 있는경우가 많으니까요 ^^..;;

2023-01-26 02:41 UTC, scolleck approved these changes
고생하셨습니다~ 궁금한 부분에 대해서는 코멘트 달아두었습니다 :)

2023-01-26 02:41 UTC, merged