[baero.kero] 예약 시스템 1, 2차 입니다
2023newkrew/spring-roomesacpe-auth-kakao pull request #71
Opened 2023-01-25 00:56 UTC by BaeRoNuI

스켈레톤 코드가 있었고, 저희가 코드를 추가하는 식으로 이번 미션이 진행되었습니다.

도메인 중 Auth는 새로 만들었고, reservation 일부 수정하였습니다.

Password 평문 그대로 저장하는것은 좀 아닌것 같아 dependency에 spring-security 추가, BCryptPasswordEncoder 활용하였습니다.

2023-01-26 05:56 UTC, teddy-ready requested changes
스켈레톤으로 구조가 잡혀있다고 하여 전체 패키지 구조는 리뷰하지 않았습니다
커멘트만 참고 하셔서 수정 주시면 머지 드립니다~

2023-01-26 05:56 UTC, teddy-ready commented on src/main/java/nextstep/global/util/PasswordUtility.java
> +
PasswordEncoder passwordEncoder 를 직접 Bean 으로 등록하지 않은 이슈가 있을까요? 
메소드 내용이 거의 동일하여 wrapping 한 이유가 있는지 궁금합니다만...

2023-01-26 05:56 UTC, teddy-ready commented on src/main/java/nextstep/global/util/JwtTokenProvider.java
MalformedJwtException
ExpiredJwtException
UnsupportedJwtException
SignatureException 

이런걸로 JWT 유효성을 try catch 로 검증하면 좋을듯합니다~

2023-01-26 05:56 UTC, teddy-ready commented on src/main/java/nextstep/global/resolver/AuthenticationPrincipalArgumentResolver.java
> +
헤더 인증 정보 추출은 유틸로 분리하는게 좋을듯합니다

public class AuthorizationHeaderExtractor {
    public static final String AUTHORIZATION = "Authorization";
    public static final String BEARER = "Bearer";
    public static final String BASIC = "Basic";

    public static String extract(HttpServletRequest request, String type) {
        Enumeration<String> headers = request.getHeaders(AUTHORIZATION);
        while (headers.hasMoreElements()) {
            String value = headers.nextElement();
            if (value.toLowerCase().startsWith(type.toLowerCase())) {
                return value.substring(type.length()).trim();
            }
        }

        return Strings.EMPTY;
    }
}

2023-01-26 05:56 UTC, teddy-ready commented on src/main/java/nextstep/member/dto/MemberRequest.java
> +    private String phone;
리퀘스트 객체 만드실때는 유효성 검증을 위해서 javax.validation.constraints 패키지 하위에 어노테이션 설정하시고, 컨트롤러에서 아큐먼트 받을때에 @Vaild 어노테이션 추가하시는 것이 좋습니다.

    @NotNull
    private String name;

이런식으로해서 ...

2023-01-27 10:54 UTC, BaeRoNuI commented
PasswordEncoder 를 직접적으로 등록시키지 않은 이유는 기존 코드에 있던 JwtTokenProvider가 @Component로 등록되어 있었기 때문에 (Controller, Service, Repository가 아닌 Utility성 Class) "config를 위한 class를 추가하고 따로 bean으로 등록하기보다는 전체적인 일관성을 지키는 것이 좋지 않을까..?" 하는 이유였습니다. config class가 있는 것을 잊고 있어서 생겼던 필요없는 class 였던 것 같습니다..

말씀해주신 Exception 들을 활용할 방법을 고민하다가, Custom Exception이 프로그래머가 핸들링 하고 있는 exception이라는 의미를 준다고 생각하여 분기를 나누고 Custom Exception을 throw 하였습니다.

리뷰 감사드립니다!

2023-01-30 03:40 UTC, teddy-ready approved these changes
머지할게요~ 수고하셨습니다~

2023-01-30 03:40 UTC, merged