[jaws.bar] 방탈출 인증 관리 3단계
2023newkrew/spring-roomesacpe-auth-kakao pull request #72
Opened 2023-01-25 02:56 UTC by park0503

## 구현 기능
- [3단계 요구 사항](https://edu.nextstep.camp/s/GiKTqpMP/ls/4djIm1J0)에 맞춰 구현했습니다.
- admin용 Interceptor를 따로 구현하고 중복 코드는 상속을 통해 최소화 했습니다.
  - 기존의 LoginInterceptor를 AdminInterceptor가 상속합니다.
- 유저의 role을 판단할 수 있는 필드 authority를 Meber 클래스 / 테이블에 생성해 주었습니다.
- 관리자 api인 멤버 전체 조회 api를 구현했습니다.
  - 해당 api의 e2e 통합 테스트를 작성했습니다.
## 궁금점
- 멤버 전체 조회 api 외 관리자 api는 차차 구현해 나갈 예정입니다. 다만 궁금한 점이, 관리자 api와 일반 api의 컨트롤러를 분리해야 하는 것은 자명하나 서비스 클래스의 경우 분리하는 것이 맞는지 분리하지 않는 것이 맞는지 확신이 서지 않습니다. 권한 판단은 Interceptor에서 진행하니 그 외에 로직 코드는 재사용하는 것이 맞는 것 같으면서도, 서비스 레이어의 코드를 보면 authentication이 아닌 authorization을 수행하는 부분이 있기에 서비스 레이어 까지 분리해야 한다는 생각도 듭니다. 카야는 이에 관해 어떻게 생각하시는지 궁금합니다!

### 감사합니다.

2023-01-25 02:57 UTC, park0503 commented
왜인지 모르겠는데 커밋 내역이 이전 pr 것 까지 전부 뜨네요... 아마 제가 머지되기 전 브랜치를 먼저 파 작업해서 그런 것 같습니다.
[refactor: 피드백 반영 - 접근 제어자 설정, 에러처리 수정](https://github.com/next-step/spring-roomesacpe-auth-kakao/pull/72/commits/8488d5af66f35081623ccdc9a7ef4a637446303a)
위 커밋부터 확인해 주시면 됩니다!

2023-01-26 10:55 UTC, gayeon1025 requested changes
안녕하세요 죠스! 설은 잘 보내셨나요? 
늦어지게 되어 죄송합니다ㅠㅠ 


> 서비스 레이어의 코드를 보면 authorization을 수행하는 부분이 있기에 서비스 레이어 까지 분리해야 한다는 생각도 듭니다.

서비스 레이어에서 authorization을 수행하는 곳이 어디인지 못 찾았는데 어디인지 말씀주시면 조금 더 상세한 답변 다시 드리도록 하겠습니다!

그래도 먼저 죠스의 질문에 답변 드려보도록 할게요! 
설계와 관련한 부분이라 물론 정답은 없고 상황에 따라 다를 것 같아요.

고민되는 지점

> Q. 어드민에서도 일반 사용자 어플리케이션과 마찬가지로 id로 유저를 조회하는(findById)가 필요한데, MemberAdminService에도 동일하게 findById()를 두 벌로 작성해야할까?

와 같은 부분이라고 생각되는데요.

1.어플리케이션이 크지 않다면 MemberService에 admin기능을 함께 작성하는 방법
   - 단, 아무곳에서나 불릴 수 없게 admin을 위한 메서드는 (aop를 활용해) @NeedAuthorization등과 같은 어노테이션으로 구분하여 admin인 경우에만 불릴 수 있도록 할 것 같아요.

2.그런데 어플리케이션의 규모가 커진다면..?
  - 만약 멤버 조회 시에 어드민 유저와 일반 유저에게 보여져야할 정보가 달라지기 시작함...
  - 위와 같은 고민으로 인해 어드민 어플리케이션과 일반 어플리케이션을 따로 나누어 띄우자! 
  - 📌 [멀티모듈 프로젝트](https://velog.io/@soyeon207/%EC%8A%A4%ED%94%84%EB%A7%81-%EB%B6%80%ED%8A%B8-%EB%A9%80%ED%8B%B0-%EB%AA%A8%EB%93%88-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EB%A7%8C%EB%93%A4%EA%B8%B0)
  - 공통관심사인 domain을 admin-app과 web-app(일반 유저용)이 바라보도록 설계하면 자연스럽게 서비스 레이어가 나뉠 것 같네요.
+ 멀티모듈이 생소하고 어려우니 반영했으면 하는 내용은 아니고 참고사항으로 답변을 달아보았습니다.  (혹시나 궁금하시면 해보셔도 저는 찬성입니다ㅋㅋ 😎)

확장을 고려하지 않아도 보통 어드민과 일반 유저의 행동이 완전히 동일하지 않고, 어드민 페이지에서의 요구 사항을 반영하느라 일반 유저에게 보여져야할 정보가 잘못 수정되거나 장애가 발생할 수 있으니 저는 분리하는 걸 선호하긴 합니다!

2023-01-26 10:55 UTC, gayeon1025 commented on src/main/java/nextstep/interceptor/AdminInterceptor.java
> +        }
어드민 api를 사용하기 위해서는 로그인이 전제되어야하므로, 로그인이 되지 않았을 때에도 exception을 던져야할 것 같은데 어떻게 생각하시나요??

2023-01-26 10:55 UTC, gayeon1025 commented on src/test/java/nextstep/member/MemberAdminE2ETest.java
> +    @DisplayName("일반 유저 권한으로는 전체 멤버를 조회할 수 없다.")
여기 오타인 것 같아요ㅎㅎㅎ 조회 -> 삭제로 변경되어야할 것 같습니다!

2023-01-30 01:19 UTC, park0503 commented on src/main/java/nextstep/interceptor/AdminInterceptor.java
> +        }
해당 검증은 super.prehHandle , 즉 LoginInterceptor의 preHandle 메소드 내에서 이뤄집니다!

2023-01-30 01:22 UTC, park0503 commented on src/test/java/nextstep/member/MemberAdminE2ETest.java
> +    @DisplayName("일반 유저 권한으로는 전체 멤버를 조회할 수 없다.")
헛 정말이네요. 수정하겠습니다!

2023-01-30 01:28 UTC, park0503 commented
> 안녕하세요 죠스! 설은 잘 보내셨나요? 늦어지게 되어 죄송합니다ㅠㅠ
> 
> > 서비스 레이어의 코드를 보면 authorization을 수행하는 부분이 있기에 서비스 레이어 까지 분리해야 한다는 생각도 듭니다.
> 
> 서비스 레이어에서 authorization을 수행하는 곳이 어디인지 못 찾았는데 어디인지 말씀주시면 조금 더 상세한 답변 다시 드리도록 하겠습니다!
> 
> 그래도 먼저 죠스의 질문에 답변 드려보도록 할게요! 설계와 관련한 부분이라 물론 정답은 없고 상황에 따라 다를 것 같아요.
> 
> 고민되는 지점
> 
> > Q. 어드민에서도 일반 사용자 어플리케이션과 마찬가지로 id로 유저를 조회하는(findById)가 필요한데, MemberAdminService에도 동일하게 findById()를 두 벌로 작성해야할까?
> 
> 와 같은 부분이라고 생각되는데요.
> 
> 1.어플리케이션이 크지 않다면 MemberService에 admin기능을 함께 작성하는 방법
> 
> * 단, 아무곳에서나 불릴 수 없게 admin을 위한 메서드는 (aop를 활용해) @NeedAuthorization등과 같은 어노테이션으로 구분하여 admin인 경우에만 불릴 수 있도록 할 것 같아요.
> 
> 2.그런데 어플리케이션의 규모가 커진다면..?
> 
> * 만약 멤버 조회 시에 어드민 유저와 일반 유저에게 보여져야할 정보가 달라지기 시작함...
> * 위와 같은 고민으로 인해 어드민 어플리케이션과 일반 어플리케이션을 따로 나누어 띄우자!
> * 📌 [멀티모듈 프로젝트](https://velog.io/@soyeon207/%EC%8A%A4%ED%94%84%EB%A7%81-%EB%B6%80%ED%8A%B8-%EB%A9%80%ED%8B%B0-%EB%AA%A8%EB%93%88-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EB%A7%8C%EB%93%A4%EA%B8%B0)
> * 공통관심사인 domain을 admin-app과 web-app(일반 유저용)이 바라보도록 설계하면 자연스럽게 서비스 레이어가 나뉠 것 같네요.
> 
> * 멀티모듈이 생소하고 어려우니 반영했으면 하는 내용은 아니고 참고사항으로 답변을 달아보았습니다.  (혹시나 궁금하시면 해보셔도 저는 찬성입니다ㅋㅋ 😎)
> 
> 확장을 고려하지 않아도 보통 어드민과 일반 유저의 행동이 완전히 동일하지 않고, 어드민 페이지에서의 요구 사항을 반영하느라 일반 유저에게 보여져야할 정보가 잘못 수정되거나 장애가 발생할 수 있으니 저는 분리하는 걸 선호하긴 합니다!

저는 레이어 분리에 대해서만 생각해 봤는데, 멀티 모듈 프로젝트를 이용해 일반 사용자용과 관리자용 애플리케이션을 따로 띄우는 방법도 있었군요! 특정 멤버 조회 등 관리자와 일반 사용자 간의 공유 기능은 재사용 가능하지 않을까 생각을 했는데 말씀하신대로 같은 내용에 대한 조회 기능이더라도 관리자용이냐, 일반 사용자용이냐에 따라 노출 정보가 달라지는 것이 일반적이겠다는 생각이 들었습니다. 다음에 관리자 기능을 구현할 일이 생긴다면 멀티 모듈 프로젝트를 적용해 보고싶네요. 좋은 정보 감사합니다!

서비스 레이어에서의 authorization은 삭제 메소드에서의 권한 확인이 있을 것 같습니다. 자신의 예약이 아니라면 exception을 터트리는 부분이 되겠네요. 관리자용 삭제에서는 저런 권한을 굳이 확인할 필요가 없다고 생각돼 드린 말씀이었습니다. 결국 카야가 알려주신 방법에 적용해 보면 1번에는 간단히 adminDelete같은 식으로 메소드를 분리해 주면 되고 2번은 애초에 애플리케이션 자체가 분리되어 있으니 이에 대해 걱정할 필요가 없겠네요!

궁금했던 부분이 많이 해결이 된 것 같습니다. 감사합니다!

2023-01-30 01:47 UTC, gayeon1025 approved these changes
월요일 오전부터 빠른 피드백 반영하시느라 고생 많으셨습니다👏👏
거의 다 왔어요~~ 💪

2023-01-30 01:47 UTC, merged