[huny.jeong] 방탈출 인증 관리 3단계
2023newkrew/spring-roomesacpe-auth-kakao pull request #73
Opened 2023-01-25 03:46 UTC by person003333

## 관리자 기능 추가하기
### Member 테이블 변화
관리자 기능을 추가하기 위해서 Member 테이블에 role 칼럼을 추가하였습니다.
그에 따른 entity, dao, dto의 변화가 있습니다.

### Intercepter
기존의 configuration에 `"/admin/**"` 조건으로 Intercepter를 잡도록 설정하고
infrastructure.web 패키지 아래 AdminInterceptor를 통해 role이 admin인지 검사하돌고 하였습니다.

2023-01-26 06:03 UTC, teddy-ready requested changes
커멘트만 한번 확인해주시면 머지합니다~

2023-01-26 06:03 UTC, teddy-ready commented on src/main/java/nextstep/infrastructure/web/JwtTokenProvider.java
>          try {
MalformedJwtException
ExpiredJwtException
UnsupportedJwtException
SignatureException
 
등을 사용하여  try catch 사용하여 유효성 검증하면 좋을것 같습니다

2023-01-26 06:03 UTC, teddy-ready commented on src/main/java/nextstep/infrastructure/web/AdminInterceptor.java
> +        if (memberId == null || !role.equals(MemberRole.ADMIN)) {
로직상 예외를 단계적으로 하는게 좋습니다

1.인증이 실패인가?
> JWT 유효성 관련된 케이스 처리 
> 해당 멤버가 DB 에 없을 경우도 있지 않은가?

2.인증은 성공이나 인가가 거부 인가?
> 권한이 없는 경우 처리

2023-01-26 06:03 UTC, teddy-ready commented on src/main/java/nextstep/domain/auth/AuthService.java
> +        String accessToken = jwtTokenProvider.createToken(member.getId().toString(), member.getRole().toString());
member.getRole().toString() 보다는 member.getRole().name() 을 사용해 보시는 것이 ENUM 을 명시적으로 이해하기 좋습니다

2023-01-30 09:50 UTC, person003333 commented
커멘트 확인했습니다. 
감사합니다~

2023-01-31 07:24 UTC, teddy-ready approved these changes
머지할게요~

2023-01-31 07:24 UTC, merged