[herbi.sf8] 방탈출 인증 관리 3단계
2023newkrew/spring-roomesacpe-auth-kakao pull request #76
Opened 2023-01-25 07:49 UTC by herbi1411

안녕하세요. 방탈출 인증 관리 3단계 리뷰 요청드립니다.
3단계는 Interceptor를 활용해서 admin관련 기능을 구현하는 것입니다. 저는 (테마, 스케줄)의 (생성, 삭제)를 admin권한이 있어야 가능하게 했습니다. admin여부 판단을 위해 Member에 role 속성을 추가했으며, jwt의 private claims에 role 값을 삽입해서 인터셉터가 토큰에서 추출한 role이 관리자일 때만 컨트롤러로 진행되도록 했습니다. 이외에 추가로 진행한 작업 내역입니다.

- Service에 Transactional 추가
- 오류 반환 코드 수정
    - 인증 관련 오류 코드 400 → 401
    - 권한 관련 오료 코드 400 → 403
- Member 도메인에 Role 추가
    - MEMBER, ADMIN 2개의 값을 가지는 enum으로 관리
    - DB에 String으로 저장
        - int ↔ string 중에 int가 메모리를 더 절약할 수 있지만 추후에 enum에 값 추가시 중간이나 처음에 값 삽입하면 지정한 역할이 바뀌는 단점이 있어서 string으로 저장
    - Member 객체 생성시 빌더에 Role 지정 안하면 MEMBER를 기본값으로 설정
- AdminInterceptor 추가
    - `/admin` URL에 대해 Interceptor 작동
    - JWT에서 토큰에 명세된 role이 admin일 때만 통과하도록 설정
- Spring App 구동시 admin 계정 1개 추가
    - ApplicationRunner를 통해 스프링 컨텍스트가 로드될 때 어드민 계정을 추가
    - 어드민 계정 정보는 application.yaml에 작성
- admin 계정만 할 수 있는 작업 설정 (조회는 모든 member 접근가능)
    - 스케줄 생성 / 삭제
    - 테마 생성 / 삭제
- TokenExtractor를 생성해서 Authorization 헤더에서 토큰값 분리 담당
- Token 요청시 username/password 인증을 MemberService의 findByUsernameAndPassword에서 담당하도록 변경 [링크](https://github.com/herbi1411/spring-roomesacpe-auth-kakao/commit/6b2f5eea1de4debcf3ac4613c746fd0aa9619339)
    - 기존에 pw 인증은 AuthService에서 담당하던 것을 MemberService에서 username과 같이 담당하도록 구조 수정
- LoginMember 도메인을 추가해서 ArgumentResolver가 LoginMember 객체를 제공하도록 수정
    - 기존에 Member를 제공하는 방식에서는 phone, name 등 필요 없는 필드와 메서드들이 같이 제공되므로 오류 발생 가능성을 방지하기 위해 도메인을 새로 추가

아까 말씀해주신 Filter에 대해서도 찾아봤는데, Filter를 사용하면 Interceptor보다 앞단에서 로직을 처리하므로 스프링 컨텍스트가 없는 로직을 처리할 때 Filter를 활용하면 안정성과 속도 면에서 좋을 것 같습니다.  일단 과제 요구사항에서 Interceptor를 활용해보라는 의도가 있는 것 같아서 Interceptor로 admin관련 로직을 구성해봤습니다!!

2023-01-26 05:41 UTC, maythree requested changes
고생 많으셨습니다.
몇가지 코멘트 남겼는데 확인 부탁드리겠습니다.

2023-01-26 05:41 UTC, maythree commented on src/main/java/nextstep/auth/JwtTokenExtractor.java
> +        return null;
null을 반환하여 처리하는 것은 지양하시는게 좋습니다.

2023-01-26 05:41 UTC, maythree commented on src/main/java/nextstep/admin/AdminInterceptor.java
> +        return jwtTokenProvider.getRole(token).map(s -> s.equals(Role.ADMIN.name())).orElse(false);
Admin 여부를 토큰 내의 claim 정보를 파싱해서 문자열 비교만 하여 판단하는데, 보안적으로 문제가 없을까요?? 조금 더 고민해보시면 좋으실 것 같습니다.

2023-01-26 05:41 UTC, maythree commented on src/main/java/nextstep/auth/AuthController.java
> +            throw new AuthorizationExcpetion(RoomEscapeExceptionCode.AUTHORIZATION_FAIL);
오타인것 같네요.

2023-01-26 05:41 UTC, maythree commented on src/main/java/nextstep/member/MemberService.java
> +@Transactional
여기에 Transcational이 선언되면 해당 서비스 하위에 메소드들은 어떻게 작동이 되는지 알고계실까요??
Trnasactional이 선언이 되어있거나, 아니라면 선언되어있지 않거나

2023-01-26 05:41 UTC, maythree commented on src/main/java/nextstep/schedule/ScheduleService.java
> +    @Transactional(readOnly = true)
이렇게 선언하여 처리하신 이유가 있으실까요??

2023-01-26 05:41 UTC, maythree commented on src/main/java/nextstep/support/applicationRunner/RoomEscapeApplicationRunner.java
> +public class RoomEscapeApplicationRunner implements ApplicationRunner {
이렇게 초기 데이터를 생성하신 이유가 따로 있으실까요?? DB가 초기화가 되어 있지 않은 상태라면, admin은 중복으로 생성되거나 오류가 발생되지 않을까요??
https://www.baeldung.com/spring-boot-data-sql-and-schema-sql
해당 부분을 알고계실수도 있지만 모르시다면 참고해보시면 좋으실 것 같습니다.

2023-01-30 00:07 UTC, herbi1411 commented on src/main/java/nextstep/auth/JwtTokenExtractor.java
> +        return null;
null을 반환하던 부분을 Optional을 사용해 empty 값을 반환하도록 수정했습니다!

2023-01-30 00:07 UTC, herbi1411 commented on src/main/java/nextstep/admin/AdminInterceptor.java
> +        return jwtTokenProvider.getRole(token).map(s -> s.equals(Role.ADMIN.name())).orElse(false);
admin여부를 판단할 때 DB에서 멤버정보 조회하는 쿼리를 하지 않고 판단하게 해보고 싶었는데 현재 구조에서는 username 값은 검증하지 않고 role만 검증하는 형식이 됐네요. 이 방식대로 하면 어드민 계정이 삭제됐는데 토큰 유효기간이 남아있으면 계속 어드민 권한에 접근 가능한 문제도 생길 것 같습니다. 적절하지 않은 것 같아서 DB 조회를 해서 검증하도록 변경했습니다. claim 값은 필요 없어져서 제거했습니다!

2023-01-30 00:07 UTC, herbi1411 commented on src/main/java/nextstep/auth/AuthController.java
> +            throw new AuthorizationExcpetion(RoomEscapeExceptionCode.AUTHORIZATION_FAIL);
Exception을 Excpetion이라고 했었네요. 해당 부분이 username, password로 계정을 인증하는 과정이라 실패한 경우 Authorization → Authentication 으로 바꾸는 것이 맞는 것같기도 해서 이름을 바꿔봤습니다. 로그인 실패 때 HttpStatus 값을 어떤 값을 줘야하는 지 검색해봤는데 401을 쓴다고 해서 상태값은 원래대로 사용했습니다!

2023-01-30 00:07 UTC, herbi1411 commented on src/main/java/nextstep/member/MemberService.java
> +@Transactional
클래스에 Transactional이 선언 되면 하위 메소드들 전부에 적용되는 것으로 알고 있습니다! 메서드 단에서 Transactional을 다시 작성하면 메서드의 Transactional 설정되로 작동합니다. MemberService의 경우 create은 클래스에 정의한 Transactional 속성대로 작동하고, 나머지 2개의 메서드는 메서드에 정의한대로 readonly가 적용돼서 작동할 것 같습니다.

2023-01-30 00:07 UTC, herbi1411 commented on src/main/java/nextstep/schedule/ScheduleService.java
> +    @Transactional(readOnly = true)
`findByThemeIdAndDate` 메서드에 readonly 속성을 붙인 이유를 말씀하신 걸까요?? 조회만 발생하는 경우에 readonly 속성으로 약간의 성능 향상을 가져올 수 있다고 봐서 readonly를 붙였습니다. 성능 향상을 가져오는 방법으로는 쿼리 최적화, 읽기 전용 connection 생성, JPA인 경우 플러시를 하지 않는 것 등이 있다고 공부했습니다.

2023-01-30 00:07 UTC, herbi1411 commented on src/main/java/nextstep/support/applicationRunner/RoomEscapeApplicationRunner.java
> +public class RoomEscapeApplicationRunner implements ApplicationRunner {
문서를 읽어보니 data.sql을 통해 초기 데이터를 지정하는 방법이 나와있네요. 전에 있던 과제에서 DB 설정 부분에 대해 알아보다가 data.sql에 초기 데이터를 지정할 수 있다는 방법을 알게 됐지만, 스프링 앱을 실행하고 특정 코드를 실행하는 방법을 통해서 해보고 싶어서 ApplicationRunner를 활용해 봤습니다. 하지만 말씀해주신대로 현재처럼 앱이 실행될 때마다 DB가 새로 생성되는 구조에서는 괜찮겠지만 실제 DB가 도입되면 문제가 발생할 것 같습니다. data.sql로 관리자를 삽입하도록 변경했습니다!

2023-01-30 01:05 UTC, maythree commented on src/main/java/nextstep/admin/AdminInterceptor.java
> +        return jwtTokenProvider.getRole(token).map(s -> s.equals(Role.ADMIN.name())).orElse(false);
말씀해주신 부분도 문제가 되지만, claim의 경우 쉽게 변조가 가능하므로 보안적으로 문제가 발생할 수 있으니 이 부분도 참고하시면 좋으실 것 같습니다.

2023-01-30 08:56 UTC, herbi1411 commented on src/main/java/nextstep/admin/AdminInterceptor.java
> +        return jwtTokenProvider.getRole(token).map(s -> s.equals(Role.ADMIN.name())).orElse(false);
네. 보안에 관련된만큼 더 조심히 사용해야겠네요. 감사합니다!

2023-01-31 00:18 UTC, maythree approved these changes
고생많으셨습니다👍👍

2023-01-31 00:18 UTC, maythree commented on src/main/java/nextstep/admin/AdminInterceptor.java
> +    private final MemberDao memberDao;
구성해놓으신 MemberService를 사용하시는게 더 좋으실 것 같습니다.

2023-01-31 00:19 UTC, merged