[verus.j] 3단계 관리자 기능
2023newkrew/spring-roomesacpe-auth-kakao pull request #80
Opened 2023-01-25 08:33 UTC by wilgur513

테마 추가 및 삭제를 관리자 계정으로 할 수 있도록 수정했습니다. 관리자에 대한 인증/인가도 Interceptor에서 이뤄지도록 했습니다~

2023-01-25 11:18 UTC, parksjin01 requested changes
1,2 단계에서 코멘트 드렸던 내용을 적용하고, 미션 요구사항에 맞게 인터셉터를 활용해서 테마 생성, 삭제시 인증 및 어드민 권한 체크를 진행해주셨네요 👍 
PR 요청주신 것을 보며 몇가지 코멘트를 남겨두었는데요, 확인 부탁드릴게요 :)

2023-01-25 11:18 UTC, parksjin01 commented on src/main/java/nextstep/auth/AdminInterceptor.java
> +        long id = Long.parseLong(jwtTokenProvider.getPrincipal(token));
`AuthenticationPrincipalArgumentResolver` 에 중복되는 코드가 있는데요,
권한에 따라서 인증하는 방법이 달라지다보니 중복 코드가 생긴것 같아요.
혹시 중복코드를 제거하는 방법이 있을까요?

2023-01-25 11:18 UTC, parksjin01 commented on src/main/java/nextstep/auth/AuthAdvice.java
>      }
에러 발생시 로그를 찍어 주셨네요 👍 
클래스명과 `@ExceptionHandler` 에서 처리하는 예외들을 볼 때 인증 관련 에러는 전부 이 클래스에서 처리하는 것을 의도하신 것 같은데 맞을까요?

만약 인증 관련 에러를 전부 이 클래스에서 처리하고자 하셨다면, 다른 컨트롤러에 포함된 `@ExceptionHandler`에서 에러 처리가 되는 경우가 있는지 확인해주시면 좋을것 같아요.
`ReservationController` 에서는 모든 Exception을 처리하는 핸들러가 있어서 위 클래스에서 처리되지 않을 것 같아요

2023-01-25 11:18 UTC, parksjin01 commented on src/main/java/nextstep/auth/AdminInterceptor.java
> +        }
어드민 권한이 없어서 에러가 발생하는 경우 `Forbidden` 에러 전달을 고려해보는 것은 어떨까요?

Unauthorized와 Forbidden 에러를 설명한 문서를 발견해서 참고하실 수 있도록 공유드려요.
https://auth0.com/blog/forbidden-unauthorized-http-status-codes/

2023-01-25 11:18 UTC, parksjin01 commented on src/main/java/nextstep/reservation/ReservationController.java
>      }
`UnauthorizedException` 발생시에도 400 응답이 전달될 것 같은데요, 401 응답 코드가 전달되도록 변경해보는 것은 어떨까요?

2023-01-25 11:18 UTC, parksjin01 commented on src/main/java/nextstep/reservation/ReservationResponse.java
> +    @JsonCreator
제가 `@JsonCreator` 어노테이션을 처음 봐서 해당 어노테이션의 역할이 궁금합니다.

2023-01-25 11:18 UTC, parksjin01 commented on src/main/java/nextstep/schedule/ScheduleController.java
> +import org.springframework.web.bind.annotation.RestController;
`createSchedule` 메소드에 코멘트를 달수 없어서 여기에 달아둡니다.

 만약 동일 theme, 동일 date, 동일 time으로 여러 스케줄이 등록 된다면
해당 스케줄들은 중복으로 판단하고 에러 응답을 전달하도록 처리해보는 것은 어떨까요?

2023-01-25 11:18 UTC, parksjin01 commented on src/main/java/nextstep/theme/ThemeController.java
>      }
테마를 등록할 때 사용자가 전달한 값을 검증해보면 어떨까요?

2023-01-25 11:18 UTC, parksjin01 commented on src/test/java/nextstep/theme/ThemeE2ETest.java
> +    }
다른 테스트 코드에서도 토큰 생성을 위한 코드가 중복되는 것 같았는데요,
토큰 생성 코드의 중복을 제거할 수 있는 방법이 있을까요?

테스트에 사용되는 코드이지만, 수정이 필요해졌을 때 중복되는 코드를 모두 고쳐야하는 것이 번거로울것 같아서요

2023-01-25 11:18 UTC, parksjin01 commented on src/test/java/nextstep/theme/ThemeE2ETest.java
>          ThemeRequest body = new ThemeRequest("테마이름", "테마설명", 22000);
어드민 권한이 추가됨에 따라서 테스트 코드도 함께 변경해주셨네요 👍 
어드민 사용자가 아닌 일반 사용자가 테마를 생성, 삭제하는 경우도 테스트 코드에 추가해보는 것은 어떨까요?
테스트 코드 추가시 테마 생성, 삭제 권한 체크와 관련해서 더 많은 케이스를 테스트 코드로 확인해볼 수 있을 것 같아요.

2023-01-31 06:27 UTC, wilgur513 commented on src/main/java/nextstep/auth/AdminInterceptor.java
> +        long id = Long.parseLong(jwtTokenProvider.getPrincipal(token));
PrincipalExtractor 클래스를 추출해서 중복 제거했습니다~

2023-01-31 06:31 UTC, wilgur513 commented on src/main/java/nextstep/auth/AuthAdvice.java
>      }
Controller에 있는 예외 처리 핸들러를 컨트롤러 어드바이스로 옮겼습니다~

2023-01-31 07:03 UTC, wilgur513 commented on src/main/java/nextstep/reservation/ReservationResponse.java
> +    @JsonCreator
Jackson에서 deserialize할 때 객체 생성 시 사용할 생성자를 선택할 수 있게 해줍니다. 보통 기본 생성자를 사용하고 필드에 주입하는 방식으로 deserialize하는데 지금은 기본 생성자가 없어서, 객체 생성시 사용할 생성자를 지정하는데 사용했습니다.

2023-01-31 07:04 UTC, wilgur513 commented on src/main/java/nextstep/schedule/ScheduleController.java
> +import org.springframework.web.bind.annotation.RestController;
BadRequest로 처리했습니다~

2023-01-31 07:04 UTC, wilgur513 commented on src/main/java/nextstep/auth/AdminInterceptor.java
> +        }
변경했습니다

2023-01-31 07:04 UTC, wilgur513 commented on src/main/java/nextstep/reservation/ReservationController.java
>      }
변경했습니다~

2023-01-31 07:15 UTC, wilgur513 commented on src/main/java/nextstep/theme/ThemeController.java
>      }
검증 로직 추가했습니다~

2023-01-31 07:19 UTC, wilgur513 commented on src/test/java/nextstep/theme/ThemeE2ETest.java
> +    }
AbstractE2ETest를 만들어서 상속을 통해 중복 코드를 제거했습니다~

2023-01-31 07:24 UTC, wilgur513 commented on src/test/java/nextstep/theme/ThemeE2ETest.java
>          ThemeRequest body = new ThemeRequest("테마이름", "테마설명", 22000);
일반 사용자가 테마를 추가 및 삭제하는 케이스 추가했습니다~

2023-02-01 03:13 UTC, parksjin01 commented on src/main/java/nextstep/auth/AuthAdvice.java
>      }
`@RestControllerAdvice`를 사용해서 `@ExceptionHandler`들을 하나의 클래스로 모아주셨네요 👍 
`ExceptionAdvice` 클래스를 보며 각 예외별 에러 처리 로직을 확인할 수 있어서 좋은것 같아요 
예외 메시지도 로그로 남겨 주셨네요 😄

2023-02-01 04:42 UTC, parksjin01 commented on src/main/java/nextstep/reservation/ReservationResponse.java
> +    @JsonCreator
베루스 덕분에 새로운 지식을 얻었네요 😄 
저는 Jackson을 사용해 deserialize를 할때에는 기본 생성자를 많이 사용해서 생소하게 느껴졌네요.
추후 기본 생성자가 없는 클래스의 deserialize가 필요할 때 사용해볼 수 있을 것 같네요 

`@JsonCreator`를 추가해주신 것을 보면 `ReservationResponse` 클래스도 `JSON`을 받아서 deserialize하는 경우가 있는걸까요?

2023-02-01 04:52 UTC, parksjin01 approved these changes
코멘트 반영해주신것 확인했습니다~
PR 머지하겠습니다. 미션 진행하시느라 고생하셨습니다 👏 👏

2023-02-01 04:52 UTC, merged