[william.watson] 인증 관리 3단계
2023newkrew/spring-roomesacpe-auth-kakao pull request #81
Opened 2023-01-25 12:05 UTC by gkwodn1044

2023-01-26 06:55 UTC, parksjin01 requested changes
윌리엄~ 설 명절 잘 보내셨나요?
3단계 미션의 요구사항에 맞게 인터셉터를 사용해서 admin 권한을 체크해주셨네요 👍 
요청주신 PR에서 몇가지 코멘트를 남겨두었는데요, 확인 부탁드릴게요 :)
애매한 부분이나 궁금한 내용이 있으시다면 언제든 편하게 연락해주세요~

2023-01-26 06:55 UTC, parksjin01 commented on src/main/java/nextstep/admin/AdminController.java
> +    }
사용자가 전달하는 값들을 체크해보는 것은 어떨까요?
지금은 테마의 가격에 음수 입력이 가능하고, 테마 제목도 DB의 컬럼 길이보다 길게 전달해서 DB Exception이 발생할 수 있을것 같아요

2023-01-26 06:55 UTC, parksjin01 commented on src/main/java/nextstep/auth/AuthService.java
> +        return jwtTokenProvider.createToken(String.valueOf(member.getId()));
토큰에 포함된 데이터를 `username`에서 `id`로 변경해주셨네요 👍 
JWT 토큰은 토큰에 포함된 데이터를 볼 수 있기 때문에 민감한 데이터는 전달하지 않는 것이 좋은것 같아요

2023-01-26 06:55 UTC, parksjin01 commented on src/main/java/nextstep/support/interceptor/AdminHandlerInterceptor.java
> +        String token = request.getHeader(HttpHeaders.AUTHORIZATION);
HTTP `Authorization` 헤더의 값은 `<auth-scheme> <authorization-parameters>` 구조를 갖고 있고
기존에는 `auth-scheme` 값으로 `Bearer`를 사용했는데요.
(아래는 관련 문서입니다.)
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization
https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#authentication_schemes

작성해주신 코드에는 `auth-scheme` 부분을 처리하는 로직이 없어서 `Bearer`도 토큰 값으로 처리될 것 같은데요,
혹시 `Bearer` 값을 제거하는 로직을 수정하신 이유가 있으실까요?

2023-01-26 06:55 UTC, parksjin01 commented on src/main/java/nextstep/support/interceptor/AdminHandlerInterceptor.java
> +        }
토큰이 유효하지 않은 경우 예외를 던지는 대신 상태코드만 변경하는데요.
`UnauthorizedException`을 던지고 `@ExceptionHandler`를 사용해서 에러 응답 및 401 상태 코드가 전달되도록 수정해보는 것은 어떨까요?

2023-01-26 06:55 UTC, parksjin01 commented on src/main/java/nextstep/support/resolver/AuthenticationPrincipalArgumentResolver.java
>          assert jwtTokenProvider.validateToken(token);
assert로 토큰이 유효한지 체크하게 되면 JAR 실행시 `-ea` 옵션을 전달해야하고, 
토큰이 유효하지 않은 경우 `AssertionError`가 발생하면서 500에러가 전달되는데요.

`ArgumentResolver`에서도 토큰이 유효하지 않은 경우 401 상태 코드가 전달되도록 수정해보는 것은 어떨까요?
동일한 로직으로 `AdminHandlerInterceptor`와 함께 에러처리를 할 수 있으면 더 좋을 것 같아요.

2023-01-26 06:55 UTC, parksjin01 commented on src/main/java/nextstep/support/resolver/AuthenticationPrincipalArgumentResolver.java
> +        return memberService.findById(Long.parseLong(jwtTokenProvider.getPrincipal(token)));
Authorization 헤더가 전달되지 않으면 `getPrincipal`에서 IllegalStatementException이 발생하는데요,
Authorization 헤더가 전달되지 않은 경우에도 401 상태 코드를 전달해보는 것은 어떨까요?

2023-01-26 06:55 UTC, parksjin01 commented on src/main/resources/data.spl
> +INSERT INTO member (username, password, name, phone, role) VALUES ('admin', 'admin', '관리자', '010-0000-0000', 'ADMIN');
혹시 sql 파일 확장자 대신 spl 확장자를 사용하신 것은 의도하신 걸까요?

2023-01-26 06:55 UTC, parksjin01 commented on src/test/java/nextstep/admin/AdminE2ETest.java
> +        adminToken = adminTokenResponse1.getAccessToken();
테스트 코드에서 중복되는 코드가 있는 것 같아요.
특히 관리자의 토큰을 생성하는 코드는 거의 모든 테스트 코드에서 사용되는 것 같은데요.

중복되는 코드를 제거할 수 있는 방법은 없을까요?
테스트 코드에서도 중복이 있는 경우, 이후 코드 수정이 필요할 때 번거롭고 실수하기 좋을 것 같아요.

2023-01-26 06:55 UTC, parksjin01 commented on src/test/java/nextstep/auth/AuthE2ETest.java
> +        adminToken = adminTokenResponse1.getAccessToken();
`adminTokenResponse`라는 변수명을 이미 사용했기 때문에 
`adminTokenResponse` 뒤에 1을 붙여서 변수명 중복을 피하신것 같은데요.

뒤에 1을 붙여서 변수명을 구분하는 것은 변수간 의미 차이를 나타내지도 않고, 코드를 읽을 때 햇갈릴수 있을 것 같아요.
1을 붙이는 대신 좀더 차이를 잘 구분할 수 있는 방법이 있을까요?

2023-01-26 06:55 UTC, parksjin01 commented
3단계 미션에 추가된 요구사항도 `README.md` 파일에 업데이트되면 좋을것 같아요 😄

2023-01-30 01:30 UTC, gkwodn1044 commented on src/main/java/nextstep/support/interceptor/AdminHandlerInterceptor.java
> +        String token = request.getHeader(HttpHeaders.AUTHORIZATION);
해당 부분에서 token을 출력해보았을 때 token의 값에 `Bearer`가 포함되지 않은 것을 확인해서 해당 로직이 필요하지 않다고 판단하였습니다!

2023-01-30 03:39 UTC, gkwodn1044 commented on src/main/java/nextstep/support/resolver/AuthenticationPrincipalArgumentResolver.java
>          assert jwtTokenProvider.validateToken(token);
해당 부분을 작성하긴 했지만 실제로 `ResolverException`을 던졌을 때 제가 작성한 `ExceptionHandler`가 해당 예외를 처리하는 것이 아니라 따로 처리되는 것으로 보입니다. 실제로 해당 `assert`문을 주석 처리 후 실행해도 관련 테스트가 여전히 통과하는 것을 볼 수 있습니다. 해당 부분은 어떻게 제가 작성한 `ExceptionHandler`가 처리하도록 할 수 있는지 여쭤보고 싶습니다.

2023-01-30 03:41 UTC, gkwodn1044 commented on src/main/java/nextstep/support/resolver/AuthenticationPrincipalArgumentResolver.java
> +        return memberService.findById(Long.parseLong(jwtTokenProvider.getPrincipal(token)));
Authorization 헤더가 전달되지 않을시 token에는 null 값이 담기게 되고, 해당 부분에 대한 검증은 `JwtTokenProvider` 클래스의 `validateToken`메소드에서 검증을 하고 있습니다. 다만 위와 마찬가지로 해당 부분에 대해서 예외를 던져도 제가 작성한 `ExceptionHandler`가 아닌 따로 처리가 되고 있어 `BAD REQUEST` 상태코드가 전달되고 있는데, 해당 부분을 어떻게 해야 할지 여쭤보고 싶습니다.

2023-02-01 05:20 UTC, parksjin01 commented on src/main/java/nextstep/support/interceptor/AdminHandlerInterceptor.java
> +        String token = request.getHeader(HttpHeaders.AUTHORIZATION);
`AdminHandlerInterceptor`의 토큰 값에 `Bearer`가 포함되는지 여부는 사용자 요청에 따라서 달라질 것 같아요
`/admin/**` 요청시 API를 호출하는 클라이언트가 API 요청의 `Authorization` 해더에 `Bearer `라는 값을 붙이지 않는 경우
Interceptor의 `preHandle()` 메소드에서 token을 확인해도 `Bearer`가 포함되어 있지 않을것 같아요.

따라서 API 호출시 `Authorization` 헤더로 토큰을 전달할 때 아래처럼 스킴을 포함하지 않고 토큰 값만 전달하는 것으로 스펙을 정한다면, `Bearer` 값을 제거하는 로직이 필요하지 않을것 같아요
```
POST /admin/themes
Host: localhost:8080
Authorization: ${Token}
```
---
참고로 저희 파트에서는 API 호출시 인증 수단중 하나로 OAuth2 스펙에 맞는 Bearer 타입의 Access Token을 사용하고 있는데요.
OAuth2 스펙에서는 `Authorization` 헤더로 Bearer 타입 토큰을 전달하는 경우, 
`Authorization` 헤더에 `Bearer`라는 스킴을 사용하도록 가이드하고 있습니다.
- OAuth2 스펙 문서: https://www.rfc-editor.org/rfc/rfc6750

2023-02-01 05:43 UTC, parksjin01 commented on src/main/java/nextstep/support/resolver/AuthenticationPrincipalArgumentResolver.java
>          assert jwtTokenProvider.validateToken(token);
`resolveArgument`에서 예외를 던졌을때 해당 예외에 맞는 에러 응답을 전달해주고 싶으시다면 
`@ControllerAdvice` 애노테이션을 사용해보실 수 있을 것 같아요.
(`@ControllerAdvice`와 `@ResponseBody`를 메타 에노테이션으로 사용하는 `@RestControllerAdvice`도 있습니다.)

`@ControllerAdvice`를 사용하면 ArgumentResolver에서 발생한 에러도 `@ExceptionHandler`를 사용해서 처리할 수 있습니다.
아래 글도 참고해보시면 좋을것 같아요 😄 
https://www.baeldung.com/exception-handling-for-rest-with-spring

관련해서 추가로 궁금한 내용이 있으시다면 편하게 말씀해주세요~

2023-02-01 05:57 UTC, parksjin01 commented on src/main/java/nextstep/support/resolver/AuthenticationPrincipalArgumentResolver.java
> +        return memberService.findById(Long.parseLong(jwtTokenProvider.getPrincipal(token)));
위 댓글에서 답변 드렸습니다~
`ArgumentResolver`도 `DispatcherServlet` 내부에서 사용되기 때문에, 
에러 발생시 스프링 MVC의 예외 처리 로직을 사용해서 예외 처리 및 에러 응답을 전달할 수 있습니다.

`ArgumentResolver`에서 에러가 발생하는 경우 `DispatcherServlet`의 `processHandlerException` 메소드가 호출되고 
해당 메소드에서 예외를 처리할 수 있는 `ExceptionResolver`를 찾아서 에러 처리 및 에러 응답을 얻어오는 것 같네요.

2023-02-01 06:57 UTC, gkwodn1044 commented on src/main/java/nextstep/support/resolver/AuthenticationPrincipalArgumentResolver.java
>          assert jwtTokenProvider.validateToken(token);
`@RestControllerAdvice`는 이미 사용하고 있었는데 레거시 코드에서 `ReservationController`에 `@ExceptionHandler`가 정의되어 있는 것을 못봤습니다. 해당 부분을 주석처리하고 테스트를 실행하니 정상적으로 예외처리가 되는 것을 확인했습니다!

2023-02-01 07:57 UTC, parksjin01 commented on src/main/java/nextstep/admin/AdminController.java
> +    }
사용자 입력값 검증을 위해 `ThemeService`에 `validateTheme` 메소드를 만들어주셨네요 👍 
지금처럼 길이를 체크하거나 정수값의 범위를 체크하는 간단한 유효성 검증은 스프링의 유효성 검증을 사용해보는 것도 좋을것 같아요
비즈니스 로직을 바탕으로 유효성 검증이 필요하다면 만들어주신 것처럼 유효성 체크를 위한 메소드를 사용하는 것도 좋은것 같아요.

2023-02-01 09:13 UTC, parksjin01 approved these changes
코멘트 반영해주신 것 확인했습니다~
관련해서 추가로 몇가지 코멘트를 남겨두었는데요, 참고만 해주시면 좋을것 같아요 🙂 
PR 머지하겠습니다. 고생하셨습니다 :)

2023-02-01 09:13 UTC, parksjin01 commented on src/main/java/nextstep/admin/AdminController.java
> +        }
`try-catch`로 예외 발생시 에러 응답을 전달해줘도 되지만, `@ExceptionHandler`를 사용해보는 것은 어떨까요?
다른 컨트롤러에서 발생하는 예외는 모두 `@ExceptionHandler`로 처리가 되고 있어 동일하게 처리가 되면 좋을것 같아요

2023-02-01 09:13 UTC, parksjin01 commented on src/main/java/nextstep/support/exception/handler/ExceptionHandler.java
> +public class ExceptionHandler {
`ExceptionHandler` 이름이 중복되어 스프링의 애노테이션에 패키지 명이 추가되었네요 😆 
스프링 애노테이션과 이름이 중복되지 않도록 변경해보는 것도 좋을것 같아요

2023-02-01 09:13 UTC, parksjin01 commented on src/main/java/nextstep/support/interceptor/AdminHandlerInterceptor.java
> +            throw new InterceptorExcpetion("forbidden access", HttpStatus.FORBIDDEN);
인증, 인가와 관련된 에러 발생시 토큰을 체크하는 위치에 맞춰서 예외 클래스 이름을 정해주신 것 같네요,
예외 클래스 이름을 예외가 발생한 이유에 따라 정하는 것을 고려해봐도 좋을것 같아요

위 예시에서는 토큰이 유효하지 않다면 `UnauthenticatedException`, 권한이 admin이 아니라면 `UnauthorizedException`등을 생각해볼 수 있을것 같아요.

2023-02-01 09:13 UTC, parksjin01 commented on src/main/java/nextstep/theme/ThemeService.java
> +    }
사용자 입력을 검증하기 위한 메소드를 추가해주셨네요 👍 
이번처럼 문자열 길이나, 값의 범위를 체크하는 경우에는 스프링이 제공하는 Validation을 사용해볼 수도 있을 것 같아요.
비즈니스 로직을 바탕으로 검증이 필요한 경우에는 별도 메소드를 만들어서 사용하는 것도 좋은것 같아요

2023-02-01 09:13 UTC, parksjin01 commented on src/test/java/nextstep/auth/AuthE2ETest.java
> +        adminToken = adminTokenResponse1.getAccessToken();
@gkwodn1044 
위 코드가 수정되지 않아서 코멘트를 놓치신것인지, 적절한 이름을 아직 고민중이신건지 궁금합니다.

일단 저도 적절한 이름이 있을지 고민을 해봤는데요
(적절한 변수명을 정하는 것이 매우 어려운것 같아요 😭 )

`adminTokenResponse1`을 `adminTokenResponseBody`로 변경하는 것을 생각해봤습니다.
기존 `adminTokenResponse` 이름을 변경하려고 하니 `extract()` 메소드가 반환하는 클래스인 `ExtractableResponse`를
이름에 포함하는 방법밖에 생각나지 않았는데, 
그렇게 되면 `adminTokenExtractableResponse`와 `adminTokenResponse`라는 변수명이 사용되어 햇갈릴수 있다는 생각이 들어서 `adminTokenResponse1`을 변경해보았습니다.

더 좋은 이름이 있을수 있을것 같은데요, 윌리엄이 생각하신 이름을 공유해주셔도 좋을 것 같아요~

2023-02-01 09:13 UTC, merged

2023-02-01 09:21 UTC, gkwodn1044 commented on src/test/java/nextstep/auth/AuthE2ETest.java
> +        adminToken = adminTokenResponse1.getAccessToken();
앗 해당 부분은 실수로 빼먹은 부분입니다! 다른 테스트의 경우 `TestSetUp`라는 클래스를 정의하고, 해당 클래스에 static 메소드들을 정의해 해당 메소드를 호출하는 것으로 `setUp()`을 채웠는데, 해당 static 메소드들에는 `adminTokenResponse1`을 정의할 필요없이 코드를 합쳐놓았습니다! 해당 변수가 불필요하다고 생각해 제거한 것인데, 만약에 정의할 필요가 있다면 제안해주신 이름으로 하는 것도 좋은 것 같습니다!