[kane.woz] Spring 인증 2차 PR
2023newkrew/spring-roomesacpe-auth-kakao pull request #84
Opened 2023-01-26 07:42 UTC by iamGreedy

PR 요청을 보낸다는게 ... 깜빡했군요.. 😭

# 지난 PR에서 추가로 적용한 부분
- RestControllerAdvise를 사용하는 것
- Lombok RequireArgumentsConstructor
- 컨트롤러 비즈니스 로직 분리
- 기존 데이터가 존재하는 데이터베이스에서의 테스트케이스 작성 
- MockMVC 도입, RestAssured 완전제거
- 테스트케이스 `@Transactional` 도입

# 지난 PR에 이어서 하는 이야기

지난 PR에서 이야기했던  Response에 대한 검증은 우디의 말을 듣고 한번 생각을 해 보았습니다.

> 결론정리 :  기존에 제가 사용했던 환경인 동적 타입 언어와는 달리 자바는 정적 타입 언어임으로 도입의 이득이 작고 공수가 크니 도입하지 않는 편이 더 좋을 것 같다.

## 자세한 생각 

우선 제가 응답 검증이 필요하다 여겼던 상황은 node.js의 특수성(동적 타입)에서 기인했다는 생각이 들었습니다.

Typescript 를 사용 중이였지만, 타입스크립트는 상위 집합에 해당하는 타입을 걸러내지 못하는 문제와 그 외 다양한 동적 타입 언어로서의 문제가 존재해 출력 타입에 예상치 못한 값이 추가로 섞여 들어가는 등의 일이 잦았습니다.

이 경우 대부분은 테스트케이스에서 걸러지기는 하지만 추가 필드가 섞여 들어가는 부분은 테스트케이스에서 확인하기 힘들었습니다.

그래서 출력값도 검증을 거치는 것이 좋다고 생각했습니다. 타입 체크가 명확하지 않기 때문입니다.

하지만 자바는 DTO 클래스를 만들고 이로 변환하는 과정에서 이런 문제가 발생하지 않기에 제가 이야기한 문제들이 발생할 확률이 지극히 낮거나 없습니다.

따라서 다시 생각해 보면 null 관련 문제를 제외하면 자바에서는 검증의 가치가 적을 수도 있다는 생각이 듭니다.

두번째 이야기였던 문서로서의 가치는, 우디가 현실적인 이야기를 해 주셨군요 😄
저도 어노테이션을 라벨로만 여기면 실제 값과의 차이가 나는 경우 오히려 혼선을 준다는 점은 완전히 동의합니다.

사실 위에서 이야기한 출력도 검증을 한다는 발상은 이 실제 값과의 차이를 완전히 없애버리고 그런 경우가 발생할 수 없게 막고자 하는 제 개인적인 욕망에서 왔습니다.(제가 좀 타입 검사하고 이런 걸 좋아합니다...🥴)

확실히 이건 제 생각이 과격한 측면이 있다는 생각이 듭니다.

따라서 이 부분은 저도 공부를 좀 해보고 이야기를 언젠가 다시 해 보고 싶습니다. 

지금 이야기 하기에는 제 레벨이 너무 낮군요 좀 성장해서 다시 찾아오겠습니다.

# 마지막으로 질문 좀 하겠습니다!

- 셀에서는 DTO 같은 부분에서 백엔드 프론트와 협업하기 위해서 어떤 식으로 소통하나요? 
  
  특히 특정 필드가 nullable한지 어떤지 여부같은 것들을 공유하다가 의사소통의 오류로  잘못된 값을 예상하고 코드를 짠 적이 있으신가요?

  제가 다른 친구들과 조별과제를 진행할 때에는 이런 일들이 있었는데 저희는 그냥 주먹구구로 처리해서 결국 맛있는 스파게티를 만들어버린 기억이 납니다.

  저희 셀에서는 이런 문제가 발생하면 어떻게 처리할 지 궁금합니다.

2023-01-30 02:18 UTC, mjin1220 requested changes
지난 단계에서 드렸던 의견들이 잘 적용된 것으로 보이네요!
고생하셨습니다. 👏

`@Transactional` 적용이 테스트 코드에만 되어있는데, 서비스 코드에도 꼭 적용되어야합니다~
제가 드린 의견들을 읽어보시고 보완 후 재리뷰요청 부탁드립니다 :)

> 셀에서는 DTO 같은 부분에서 백엔드 프론트와 협업하기 위해서 어떤 식으로 소통하나요?
>
> 특히 특정 필드가 nullable한지 어떤지 여부같은 것들을 공유하다가 의사소통의 오류로 잘못된 값을 예상하고 코드를 짠 적이 있으신가요?
>
> 제가 다른 친구들과 조별과제를 진행할 때에는 이런 일들이 있었는데 저희는 그냥 주먹구구로 처리해서 결국 맛있는 스파게티를 만들어버린 기억이 납니다.
> 
> 저희 셀에서는 이런 문제가 발생하면 어떻게 처리할 지 궁금합니다.

Swagger와 Postman 내 workspace를 이용하여 API I/F를 공유합니다.
nullable체크를 UI에서 옵션널 체이닝를 이용하여 null인 값이 온 경우에 대한 핸들링을 하고 있는 것으로 알고 있습니다. 그 외의 경우에는 테스트를 통해 검출하고 있습니다.

2023-01-30 02:18 UTC, mjin1220 commented on src/main/java/roomescape/command/AuthCommand.java
> -
롬복이 컴파일된 `.class` 파일을 보면 거의 동일하지만, 개발자 입장에서는 편해져서 좋습니다. 잘 반영되었네요 👏

2023-01-30 02:18 UTC, mjin1220 commented on src/main/java/roomescape/controller/Default.java
> +@RequiredArgsConstructor
[nit] `Default` 클래스에는 멤버변수가 없어서 불필요한 생성자 추가인 것으로 보여요. 필요할 때 추가하는 것은 어떤가요 ?
나중을 위해 추가하는 코드가 많을수록 기존 코드를 파악하는데 읽어야하는 코드량과 복잡도가 올라간다고 생각해서입니다.

2023-01-30 02:18 UTC, mjin1220 commented on src/main/java/roomescape/service/ThemeService.java
> +    }
Transaction 관련 설정들이 필요해보입니다.
`@Transactional`과 관련된 내용들을 찾아보시고 적용해보시면 좋을 것 같습니다!

2023-01-30 02:18 UTC, mjin1220 commented on src/main/java/roomescape/service/ReservationService.java
> +    public Reservation findReservation(@PathVariable Long id) {
`@PathVariable` 어노테이션은 Controller 에서만 사용되는 것으로 알고 있어요.
복붙이 잘못된 것이라면 변경되면 좋겠고, 아니라면 어떤 목적을 위해 사용하신 것인지 공유해주실 수 있을까요 ?

2023-01-30 02:18 UTC, mjin1220 commented on src/main/java/roomescape/controller/interceptor/AdminInterceptor.java
> +        }
일부 동일한 로직이 기존 `JWTBearerTokenSubjectResolver` 클래스에 존재하는데, 중복 코드를 줄일 수는 없을지 고민해봐도 좋을 것 같아요.

```java
        var token = jwtProvider.getTokenFromAuthHeader(webRequest.getHeader("Authorization"));
        if (token.isEmpty()) {
            throw new ServiceException(ErrorCode.INVALID_BEARER);
        }
        if (jwtProvider.isInvalidJWT(token.get())) {
            throw new ServiceException(ErrorCode.INVALID_TOKEN);
        }
```

2023-01-30 02:18 UTC, mjin1220 commented on src/main/java/roomescape/controller/errors/ErrorResponse.java
> +    public static ErrorResponse fromErrorCode(ErrorCode code) {
정적 팩토리 메서드 좋네요~
`from` 네이밍으로 사용하고 파라미터 타입으로 읽어도 좋을 것 같네요~

아래 내용은 참고에 있는 글 내용 중 일부를 인용한 내용입니다.
> 정적 팩토리 메서드 네이밍 컨벤션
> from : 하나의 매개 변수를 받아서 객체를 생성
> of : 여러개의 매개 변수를 받아서 객체를 생성

참고
- https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/

2023-01-30 02:18 UTC, mjin1220 commented on src/main/java/roomescape/controller/ThemeController.java
> +@RequestMapping()
빈 값이라면 어노테이션이 제거되어도 좋을 것 같네요.
아래 엔드포인트들을 보아하니 `/api/themes` 으로 지정되어도 좋을 것 같구용~

2023-01-30 02:23 UTC, iamGreedy commented on src/main/java/roomescape/service/ReservationService.java
> +    public Reservation findReservation(@PathVariable Long id) {
복붙이... 잘못되었습니다😭

2023-01-30 02:24 UTC, iamGreedy commented on src/main/java/roomescape/controller/errors/ErrorResponse.java
> +    public static ErrorResponse fromErrorCode(ErrorCode code) {
셀에서 본 코드를 그대로 가져와서 그렇게 느껴졌나 봅니다. 😄

2023-01-30 06:49 UTC, iamGreedy commented on src/main/java/roomescape/controller/errors/ErrorResponse.java
> +    public static ErrorResponse fromErrorCode(ErrorCode code) {
from만 써봐서 of 와의 차이는 잘 몰랐네요! 감사합니다!

2023-01-30 06:59 UTC, iamGreedy commented
---
# `@Transactional`에 대해서
이건 할 말이 없네요 명백한 제 실수입니다.

---
# 사용되지 않는 코드에 관해서

전체적으로 `@RequestMapping()`, `@RequiredArgsConstructor` 부분에서 이야기한 바와 같이 사용되지 않는 어노테이션에 대한 이야기가 많이 느껴지네요.

지금까지는 사용되지 않더라도 소스코드간의 일관성을 위해서 작성하려고 의도적으로 생략을 하지 않았는데 이부분은 쓰는 쪽으로 작성하겠습니다!

2023-01-30 07:51 UTC, iamGreedy commented on src/main/java/roomescape/controller/interceptor/AdminInterceptor.java
> +        }
컨텍스트를 쓸까 말까 고민하고 있었는데 역시 ...

다만 컨텍스트는 이번이 아닌 다음 프로젝트에서 이어받아서 진행하고 싶습니다. 혹시 다음 `spring-roomescape-waiting-kakao`프로젝트에 이어서 진행하고 싶은데 그렇게 해도 될까요?

2023-02-03 00:46 UTC, mjin1220 commented on src/main/java/roomescape/controller/interceptor/AdminInterceptor.java
> +        }
@iamGreedy 넵!

2023-02-03 00:47 UTC, mjin1220 approved these changes
재리뷰 완료했습니다 👍🏼 
피드백드렸던 것들이 잘 반영된 것 확인했고, 머지하겠습니다 :)

2023-02-03 00:47 UTC, merged