[omin.ju] 인증관리 Step3 리뷰요청입니다!
2023newkrew/spring-roomesacpe-auth-kakao pull request #89
Opened 2023-01-28 20:07 UTC by HONGMINJU

안녕하세요 사샤!
Step3 리뷰 요청드립니다.

## Step 설명
- step 1 : 토큰을 발급하는 API 생성, 내 정보 조회 API에 토큰 이용하기
- step 2 : 예약 생성/취소 API 구현 및 비로그인 사용자 접근 막기(HandlerMethodArgumentResolver를 사용하여 검증)
- step 3 : 관리자 기능 추가
(interceptor를 사용하여 검증)

---
## 패키지 구조 설명
Step1,2와 전반적인 패키지 구조는 동일하여 변경사항 위주로 설명드리겠습니다!

- auth 패키지
로그인할 때 memberRole을 받아 관리자 로그인인지 일반로그인인지 구분하였고
RequestBody에 들어오는 role은 `@ValidMemberRole`을 만들어 memberRole enum에 맞는 지 체크했습니다.
JwtTokenProvider에서 accessToken을 발급할 때 기존에는 username만 이용했었는데 추가로 memberRole도 이용하여 관리자api접근 시 권한 확인에 사용했습니다.

- common, config 패키지
AdminInterceptor와 ValidMemberRole, EnumValidator가 추가되었습니다.
   - AdminInterceptor : admin으로 시작하는 요청 시 token 내부에 있는 role이 ADMIN인 지 체크
    - ValidMemberRole, EnumValidator : request시 들어오는 역할(ADMIN, GENERAL)을 체크하는 validator

- member 패키지
관리자와 일반 사용자의 역할을 구분하는 MemberRole enum을 추가했고 
그에 따라 테이블과 sql문을 수정했습니다.

- admin, schedule, theme 패키지
scheduleController, themeController에 있던 테마 생성/삭제, 스케줄 생성/삭제 API를 따로 구분하여 admin 패키지로 이동시켰습니다.

---
## 궁금한 점
- token을 어느정도로 신뢰해야 하나요?
요청 시 들어온 accessToken이 아무문제 없이 복호화된다면 어느정도는 신뢰하고 비지니스 로직을 실행시켜도 된다고 생각했습니다. 근데 jwt secret key가 유출될 수 있다는 생각을 하면 username이 유효한 지 검사가 필요할 거 같은데...
**실무에서는 token에서 추출한 username(pk)을 가진 row가 DB에 존재하는 지에 대한 검사를 진행해야하나요?
만약 한다면 매 요청마다 DB접근이 있을 것 같은데 오버헤드가 상관 없는지, 유효성 검사는 service단에서 진행하는 지 궁금합니다!**

2023-01-31 06:48 UTC, JisooJang requested changes
오민, 지난번 피드백 드렸던 부분 잘 적용해주신것 같아서 잘보았습니다 👍 
이번 PR에서는 비교적 간단한 피드백 드렸는데요,
확인해보시고 수정해주시면 될것 같습니다!

2023-01-31 06:48 UTC, JisooJang commented on src/main/java/nextstep/auth/AuthorizationExtractor.java
> +                request.setAttribute(ACCESS_TOKEN_TYPE,
저도 NEXTSTEP 강의를 들었었지만, 항상 메서드 내에서 인덴트가 많아져서 피드백을 받았었는데요!
이 `extract` 메서드에 인덴트가 너무 많은것 같아요,  메서드 분리를 고민해보셔도 좋을것 같습니다.

2023-01-31 06:48 UTC, JisooJang commented on src/main/java/nextstep/auth/dto/TokenRequestDto.java
> +    @ValidMemberRole
👍

2023-01-31 06:48 UTC, JisooJang commented on src/main/java/nextstep/reservation/ReservationDao.java
> +        return jdbcTemplate.query(sql, rowMapper, themeId, LocalDate.parse(date));
👍

2023-01-31 06:48 UTC, JisooJang commented on src/main/java/nextstep/auth/AuthService.java
> +    public void validateUsernameAndPassword(TokenRequestDto tokenRequestDto) {
이미 다른 케이스의 경우 별도의 Validator 클래스를 구현하셔서 필요성을 아실것 같지만,
AuthService 클래스의 책임이 향후 변화에 대한 유지보수를 생각하면,
validate의 역할도 해당 클래스에 포함시킬것인지 고민해보시고 별도의 Validator로 작성하셔도 좋을것 같아요.

2023-02-02 07:53 UTC, HONGMINJU commented
사샤!!
해주신 피드백 잘보았습니다!! 좋은 피드백 덕분에 많이 배우고 있습니다.ㅎㅎ
그리고 accessToken과 refreshToken에 대해 알게 되어 좋았습니다!!!

피드백을 바탕으로 수정한 부분입니다
- extract 메소드를 분리했습니다!! 이렇게하니 메소드의 책임을 더욱 세분화할 수 있었습니다.
- 로그인 유효성(실제 member가 있는 지 확인)을 체크하는 `@ValidLoginRequest` 생성

2023-02-03 01:12 UTC, JisooJang commented
@HONGMINJU 
수정하느라 고생하셨어요!
해당 PR 잘 수정해주셔서 3단계는 이만 머지하도록 하셨습니다.
고생하셨어요 오민~

2023-02-03 01:12 UTC, merged