[minion.mo] 인증 관리 Step1, 2
2023newkrew/spring-roomesacpe-auth-kakao pull request #9
Opened 2023-01-17 01:02 UTC by dongjinBaek

제프리 안녕하세요.
방탈출 인증관리 1,2단계입니다.

- jwt 토큰 발급 / 검증은 제공된 `JwtTokenProvider` 클래스를 이용했습니다.
- 인증을 담당하는 `auth` 패키지를 추가했습니다.
- 토큰에서 username을 추출해주는 `AuthenticationPrincipalArgumentResolver` 를 추가했습니다.
- 토큰이 있어야 접근할 수 있는 예약 생성 / 취소 API는 위 어노테이션을 컨트롤러 인자에 추가했습니다.

2023-01-18 06:45 UTC, artium59 commented on src/test/java/nextstep/reservation/ReservationE2ETest.java
> +    @DisplayName("다른 사람의 예약을 삭제한다")
테스트가 이상한 것 같습니다.
동일 accessToken인데 otherName으로 저장한 것을 삭제 불가능하다면, otherName으로 만든 새로운 계정만 삭제 가능할까요?

2023-01-18 06:46 UTC, artium59 commented on src/test/java/nextstep/auth/AuthE2ETest.java
> +                .header("authorization", "Bearer " + accessToken)
여기서 `.header("authorization", "Bearer " + accessToken)` 부분을 없앤다면 401 에러가 나와야 할 것 같은데 어떻게 생각하시나요?
만약 401이 나오게 고친다면 테스트 중간중간 놓친 부분이 있는데요, 이 부분도 찾아서 추가하시면 될 것 같습니다.

2023-01-18 06:53 UTC, artium59 requested changes
진 안녕하세요. 늦어서 죄송합니다.
테스트 위주로 리뷰를 남겼는데, 확인하시고 다시 리뷰 요청 주세요.

2023-01-18 07:07 UTC, dongjinBaek commented on src/test/java/nextstep/reservation/ReservationE2ETest.java
> +    @DisplayName("다른 사람의 예약을 삭제한다")
reservation 테이블에 사용자 정보가 name 필드 밖에 없어서 생기는 문제인 것 같습니다. 
(해당 name 정보는 예약요청 post body로 들어와서, 로그인한 유저 정보를 담을 필드가 없음)

해당 테이블에 member_id 필드를 추가하고, 본인 확인도 이 필드를 통해 하도록 변경하겠습니다. (기존은 이름 일치여부 확인)

2023-01-19 02:25 UTC, dongjinBaek commented
제프리 안녕하세요. 리뷰해주신 내용 수정해봤습니다.

### 다른 사람 예약인지 여부 토큰 활용해서 하도록 수정
- [feat : reservation 테이블에 member_id 필드 추가](https://github.com/next-step/spring-roomesacpe-auth-kakao/pull/9/commits/a61a6c2d7399f56272feb95f57859e283f387c9f)
- [fix : member_id 필드 추가 후 Reservation를 찾아올 수 없던 sql 에서 수정](https://github.com/next-step/spring-roomesacpe-auth-kakao/pull/9/commits/ed082ca4cef3b183fc934d4d8540611e498d3ab9)
- [test: 다른 사람의 예약 삭제 불가능한 테스트케이스 토큰 기반으로 판별하도록 변경](https://github.com/next-step/spring-roomesacpe-auth-kakao/pull/9/commits/e2e5c764a21d02562bc44a83d19adf3907ce9a0c)

### 토큰이 없으면 401 반환 & 401 테스트케이스 추가
- 기존 코드가 토큰이 잘못되면 401 던지고 없으면 400 던지도록 되어 있어서 토큰없이 보내는 없는 예약을 삭제 요청 TC가 얻어걸려 성공하고 있었어서 같이 수정했습니다.
- [fix : @LoginUser 어노테이션이 있지만 Authorization 헤더가 없을 떄 UnAuthorizedException 던지도록 수정](https://github.com/next-step/spring-roomesacpe-auth-kakao/pull/9/commits/adf325c44bf16130cfe851c4aaf7bf40d76f4910)
- [test : 개인정보 조회 기능 테스트케이스 추가](https://github.com/next-step/spring-roomesacpe-auth-kakao/pull/9/commits/b91faeca8935c71b3337e41c1d4fb7ffa811f5a3)
- [test : 토큰이 없이 인증 필요한 API에 요청보내는 테스트케이스 추가](https://github.com/next-step/spring-roomesacpe-auth-kakao/pull/9/commits/6300b63f42c46651f2d6f117cafb50ff7dca4eb5)

### 추가) `@AuthenticationPrinciple` 어노테이션을 `@LoginUser` 로 이름 변경
- [refactor : ArgumentResolver에서 username 대신 loginMember 반환하도록 변경](https://github.com/next-step/spring-roomesacpe-auth-kakao/pull/9/commits/db676cfe8898573663f7b6894872a2346d7c702a)
- [refactor : AuthenticationPrincipal 어노테이션 이름 LoginUser로 변경](https://github.com/next-step/spring-roomesacpe-auth-kakao/pull/9/commits/3409c34f1c326b493910c023534ec4f9a3f3459b)

2023-01-19 05:26 UTC, artium59 commented on src/main/java/nextstep/auth/AuthService.java
> +        Member member = memberDao.findByUsername(username);
`username`이 pk가 아닌 것이 마음에 걸리네요. 동명이인일 경우에 문제가 생길 것 같아요.

2023-01-19 05:26 UTC, artium59 commented on src/main/java/nextstep/config/auth/LoginUserArgumentResolver.java
> +        if (header == null) {
👍

2023-01-19 05:29 UTC, artium59 approved these changes
제가 미처 놓친 부분이 있어서 코멘트 1개 남겼습니다.
이 부분은 수정할 부분이 크지 않아서 다음에 수정이 되었으면 좋겠습니다.

이 pr은 머지하겠습니다. 즐거운 설 보내세요 :)

2023-01-19 05:29 UTC, merged