[hyun.k] 방탈출 인증 관리 3단계
2023newkrew/spring-roomesacpe-auth-kakao pull request #90
Opened 2023-01-30 01:14 UTC by kimtaehyun98

안녕하세요 웨이드!

1,2 단계 미션을 boorwonie가 머지해주셔서 3단계 리뷰 요청 드립니다!

이번 미션에서 token 안에 id 값을 가지게 변경하였고, 
미션 요구사항에 맞게 테마, 스케듈 생성 및 삭제는 관리자만 가능하게 API를 변경하였습니다.

바쁘시다고 들었는데 이번 리뷰도 잘 부탁드립니다! ☺️

2023-01-30 08:15 UTC, wade-lim requested changes
고생하셨습니다!!

설 연휴 때 휴가를 써서 1, 2 단계 리뷰를 못 드렸네요 ㅠㅠ
연휴 전에 리뷰를 해보려 했는데 인증 쪽은 많이 아는게 없어서 리뷰를 완료하지 못했네요 😓

코드 관련해서는 저는 패키지 관리를 `controller` `service` `domain` `model` 와 같이 레이어나 목적별로 하는데, 비즈니스 도메인 별로 분류를 하는 것도 괜찮아보이네요~

2023-01-30 08:15 UTC, wade-lim commented on src/main/java/nextstep/config/AuthenticationMemberArgumentResolver.java
> +>>>>>>> kimtaehyun98
[확인]
merge 중 충돌이 발생한 것 같네요~

2023-01-30 08:15 UTC, wade-lim commented on src/main/java/nextstep/auth/AuthService.java
> +        String accessToken = jwtTokenProvider.createToken(String.valueOf(member.getId()));
[질문]
username 대신 id 를 기반으로 관리하게 된 계기가 있나요? (순수한 궁금증입니다 :) )

[의견]
token 에 id 정보만 포함되는건 좋은 것 같네요! 유저의 role 이 변경되거나 기타 이슈에도 유연하게 대응할 수 있을거 같아요~

2023-01-30 08:15 UTC, wade-lim commented on src/main/java/nextstep/config/AdminInterceptor.java
> +        if(member.getRole() != 0){
[확인]
요거 컴파일이 되나요?

2023-01-30 08:15 UTC, wade-lim commented on src/main/java/nextstep/config/AdminInterceptor.java
> +        Member member = memberDao.findById(id);
[의견]
사실상 `checkAdmin` 과 같은 역할을 하는 함수인 것 같아요!

`token` 을 통해 `Member` 를 조회하는 함수(ex: `getMember`?)를 분리하고, `checkAdmin` 쪽에서 이 함수를 통해 `Member` 를 조회 후 role 을 체크하는 식으로 하는건 어떨까요?

`getMember` 에서 `token` 의 nullity 와 만료 여부도 같이 검사하도록 하면 다른 `Role` 이 추가되어서 검사해야 할 때나 `Member` 에 부가 정보가 추가될 때 좀 더 확장성이 있을 것 같아요!

[추가]
`MemberService.findMemberByToken` 이 있었네요~ 요걸 사용하는건 어떨까요?

2023-01-30 08:15 UTC, wade-lim commented on src/main/java/nextstep/member/Member.java
> +        this.role = role;
[의견]
`@AllArgsConstructor` 를 사용해도 좋을 것 같아요~

2023-01-30 08:58 UTC, kimtaehyun98 commented on src/main/java/nextstep/config/AuthenticationMemberArgumentResolver.java
> +>>>>>>> kimtaehyun98
Config 패키지의 conflict들을 확인하지 못했네요ㅠㅠ 더 신경써서 테스트 하고 제출하겠습니다ㅠㅠ

2023-01-30 08:58 UTC, kimtaehyun98 commented on src/main/java/nextstep/auth/AuthService.java
> +        String accessToken = jwtTokenProvider.createToken(String.valueOf(member.getId()));
username은 중복 가능성이 있다고 생각했습니다. 그래서 username의 중복 체크 로직을 넣어줄까, id 값을 가지게 바꿀까 고민하다가 
username이 변경된다면 토큰도 새로 반환해줘야 하는 등 추후 확장성을 고려했을 때 id값을 토큰에 가지고 있는게 좋을 것 같다고 생각했습니다!

2023-01-30 08:58 UTC, kimtaehyun98 commented on src/main/java/nextstep/config/AdminInterceptor.java
> +        if(member.getRole() != 0){
엇 이부분은 enum으로 바꾸면서 신경쓰지 못했네요ㅠㅠ 수정 완료했습니다!

2023-01-30 08:59 UTC, kimtaehyun98 commented on src/main/java/nextstep/config/AdminInterceptor.java
> +        Member member = memberDao.findById(id);
이 부분은 고민했었는데 checkLogin 처럼 혹시나 관리자에 대한 다른 검증 로직이 들어갈 수도 있다고 생각해서 이처럼 구현했는데 생각해보니 지금 로직은 의미 없는 메소드 분리 같네요!

getMemberByToken 메서드를 사용하도록 변경하였습니다. ☺️

2023-01-31 07:09 UTC, wade-lim approved these changes

2023-01-31 07:09 UTC, merged