[bayne.jeong] 방탈출 인증 관리 3단계 제출합니다
2023newkrew/spring-roomesacpe-auth-kakao pull request #91
Opened 2023-01-30 01:26 UTC by jungin0507

이번 PR에서는 관리자 기능 추가 및 인증 로직 리팩토링 위주로 진행했습니다!
인증 로직은 최대한 Spring Security를 따라해보고자 노력했는데 역시 쉽지가 않네요 ㅎㅎ

## 구현 기능
- JWT 인증 필터 추가
- 인증 객체를 담기 위한 `LoginMemberContext` 추가
- 더이상 `AuthenticationPrincipalArgumentResolver` 에서 인증 로직을 수행하지 않도록 변경

2023-01-30 02:55 UTC, mjin1220 requested changes
과제 진행하시느라 고생하셨습니다. 👏

몇 가지 의견을 드렸습니다. 확인해보시고 보완 부탁드립니다.

추가로 `*Service` 클래스들에 `@Transactional` 처리가 없는데, 찾아보시고 적용해야할 것 같아요!
이것도 같이 챙겨주세요~

2023-01-30 02:55 UTC, mjin1220 commented on src/main/java/nextstep/auth/domain/LoginMember.java
> +@AllArgsConstructor(access = AccessLevel.PRIVATE)
정적 팩터리 메서드를 적용하시면서 생성자 접근제어자를 변경한 것이 좋네요 👍🏼 
`@Builder` 를 사용한 방법도 찾아보시면 좋을 것 같습니다 :)

2023-01-30 02:55 UTC, mjin1220 commented on src/main/java/nextstep/auth/domain/Role.java
> +}
`Role`을 ADMIN만 사용하는 것이 아니라 USER (기본 유저겠죠 ?)도 고려된 부분이 좋네요 👍🏼

2023-01-30 02:55 UTC, mjin1220 commented on src/main/java/nextstep/auth/filter/JwtAuthenticationFilter.java
> +        loginMemberContextHolder.setContext(loginMember);
별도의 ContextHolder를 만들어서 사용하시는데, `SecurityContextHolder`를 사용해서 구현해봐도 좋을 것 같아요 :)

2023-01-30 02:55 UTC, mjin1220 commented on src/main/java/nextstep/auth/interceptor/AdminInterceptor.java
> +        return ctx.isAdmin();
`return ctx.isAdmin();` 의 결과로 false가 반환되는 경우에 응답값이 `403 FORBIDDEN`으로 반환되지 않을 수도 있을 것 같아요. 한 번 더 체크해주실 수 있을까요 ~ ?

2023-01-30 02:55 UTC, mjin1220 commented on src/main/java/nextstep/auth/jwt/DecodedJwtToken.java
> +    private static final String secretKey = "learning-test-spring-learning-test-spring";
정적 상수는 대문자로 선언되는 것이 국룰입니다 👍🏼

2023-01-30 02:55 UTC, mjin1220 commented on src/main/java/nextstep/auth/jwt/DecodedJwtToken.java
> +    private static final String secretKey = "learning-test-spring-learning-test-spring";
다른 클래스에서도 동일한 secretKey를 가지고 있는 것으로 보입니다.
변경되는 경우 변경될 부분이 많아서 놓치게 될 수도 있어요. 한 곳에서 관리될 수 있도록 변경되는 것이 좋겠어요!

2023-01-30 02:55 UTC, mjin1220 commented on src/main/java/nextstep/member/Member.java
>      }
각 생성자마다 할당하는 부분을 가져가는 것보다는 기존 생성자를 재사용하는 것은 어떤가요 ~ ?

```java
public Member() {
     this(Role.USER);
}

public Member(Role role) {
    this.role = role;
}
```

2023-01-30 02:55 UTC, mjin1220 commented on src/main/java/nextstep/exception/handler/GlobalExceptionHandler.java
> +        e.printStackTrace();
로그를 `e.printStackTrace()`를 사용해서 출력하기보다는 logger를 사용해서 처리하는 것이 좋습니다 :)

참고
- https://tgyun615.com/59

2023-02-01 04:17 UTC, jungin0507 commented
피드백 해주신 내용하고 1,2 단계 리뷰에서 피드백 해주셨는데 반영하지 못했던 부분들도 반영 완료했습니다!

리뷰 반영 내용
- LoginMember 클래스에서 Builder 패턴 적용
- `AdminInterceptor`에서 role이 admin이 아닐때에는 Forbidden 응답이 오지 않던 현상 해결
- 상수 이름은 CONSTANT_CASE 로 선언하도록 변경
- 시크릿키를 프로퍼티로 관리하여 중복 선언 문제 해결
- `e.printStackTrace()`대신 로거를 이용
- 서비스 클래스에 `Transactional` 어노테이션 적용

이하 1,2 단계에서 피드백 해주신 사항
- Auth 관련 에러는 항상 401 에러만 반환하므로 상수화
- `ErrorResponse` 클래스에서 `ErrorCode` 객체를 받는 생성자 추가
- Bean Validation이용하여 Request 검증
- 테스트 코드에서 사용되지 않던 코드 삭제

2023-02-01 04:18 UTC, jungin0507 commented on src/main/java/nextstep/auth/filter/JwtAuthenticationFilter.java
> +        loginMemberContextHolder.setContext(loginMember);
이번 미션에서 spring security를 사용하지 않아서 이번 미션 코드에서는 적용이 어려울것 같습니다 😥

2023-02-03 01:37 UTC, mjin1220 approved these changes
재리뷰 했습니다 :)
과제 진행하시느라 고생하셨습니다. 머지할게요.

2023-02-03 01:37 UTC, mjin1220 commented on src/main/java/nextstep/auth/domain/LoginMember.java
> +@Builder
nit: `@Builder`에도 `(access = AccessLevel.PRIVATE)` 지정이 되면 좋을 것 같네요~

2023-02-03 01:37 UTC, merged